-- tests/test_gameroutes.lua -- GENERATED by tools/gen_flights.py from tools/flight_source/game_routes.txt.
-- The routes the game itself reported (/mzroutes) are ground truth: given the flight points the capturing
-- character had found, the planner (flights only, one ticket) must pick the same stops.
useTestDistances()
addon.World:Build()

local blocks = {
    {
        found = { "TAXI_2", "TAXI_6", "TAXI_7", "TAXI_4", "TAXI_12", "TAXI_5", "TAXI_71" },
        routes = {
            { "TAXI_71", "TAXI_2" },
            { "TAXI_71", "TAXI_5", "TAXI_4" },
            { "TAXI_71", "TAXI_5" },
            { "TAXI_71", "TAXI_2", "TAXI_6" },
            { "TAXI_71", "TAXI_2", "TAXI_6", "TAXI_7" },
            { "TAXI_71", "TAXI_5", "TAXI_12" },
        },
    },
    {
        found = { "TAXI_2", "TAXI_6", "TAXI_7", "TAXI_4", "TAXI_12", "TAXI_5", "TAXI_71", "TAXI_74" },
        routes = {
            { "TAXI_74", "TAXI_71", "TAXI_2" },
            { "TAXI_74", "TAXI_71", "TAXI_5", "TAXI_4" },
            { "TAXI_74", "TAXI_71", "TAXI_5" },
            { "TAXI_74", "TAXI_6" },
            { "TAXI_74", "TAXI_6", "TAXI_7" },
            { "TAXI_74", "TAXI_71", "TAXI_5", "TAXI_12" },
            { "TAXI_74", "TAXI_71" },
        },
    },
    {
        found = { "TAXI_2", "TAXI_6", "TAXI_7", "TAXI_4", "TAXI_12", "TAXI_5", "TAXI_71", "TAXI_74" },
        routes = {
            { "TAXI_5", "TAXI_2" },
            { "TAXI_5", "TAXI_4" },
            { "TAXI_5", "TAXI_71", "TAXI_74", "TAXI_6" },
            { "TAXI_5", "TAXI_71", "TAXI_74", "TAXI_6", "TAXI_7" },
            { "TAXI_5", "TAXI_12" },
            { "TAXI_5", "TAXI_71" },
            { "TAXI_5", "TAXI_71", "TAXI_74" },
        },
    },
    {
        found = { "TAXI_2", "TAXI_6", "TAXI_7", "TAXI_4", "TAXI_12", "TAXI_5", "TAXI_71", "TAXI_74" },
        routes = {
            { "TAXI_6", "TAXI_2" },
            { "TAXI_6", "TAXI_2", "TAXI_4" },
            { "TAXI_6", "TAXI_74", "TAXI_71", "TAXI_5" },
            { "TAXI_6", "TAXI_7" },
            { "TAXI_6", "TAXI_74", "TAXI_71", "TAXI_5", "TAXI_12" },
            { "TAXI_6", "TAXI_74", "TAXI_71" },
            { "TAXI_6", "TAXI_74" },
        },
    },
    {
        found = { "TAXI_2", "TAXI_6", "TAXI_7", "TAXI_4", "TAXI_12", "TAXI_5", "TAXI_71", "TAXI_74", "TAXI_8" },
        routes = {
            { "TAXI_8", "TAXI_6", "TAXI_2" },
            { "TAXI_8", "TAXI_6", "TAXI_2", "TAXI_4" },
            { "TAXI_8", "TAXI_6", "TAXI_74", "TAXI_71", "TAXI_5" },
            { "TAXI_8", "TAXI_6" },
            { "TAXI_8", "TAXI_7" },
            { "TAXI_8", "TAXI_6", "TAXI_74", "TAXI_71", "TAXI_5", "TAXI_12" },
            { "TAXI_8", "TAXI_6", "TAXI_74", "TAXI_71" },
            { "TAXI_8", "TAXI_6", "TAXI_74" },
        },
    },
    {
        found = { "TAXI_2", "TAXI_6", "TAXI_7", "TAXI_4", "TAXI_12", "TAXI_5", "TAXI_71", "TAXI_74", "TAXI_8", "TAXI_16" },
        routes = {
            { "TAXI_16", "TAXI_7", "TAXI_6", "TAXI_2" },
            { "TAXI_16", "TAXI_7", "TAXI_6", "TAXI_2", "TAXI_4" },
            { "TAXI_16", "TAXI_7", "TAXI_6", "TAXI_74", "TAXI_71", "TAXI_5" },
            { "TAXI_16", "TAXI_6" },
            { "TAXI_16", "TAXI_7" },
            { "TAXI_16", "TAXI_8" },
            { "TAXI_16", "TAXI_7", "TAXI_6", "TAXI_74", "TAXI_71", "TAXI_5", "TAXI_12" },
            { "TAXI_16", "TAXI_7", "TAXI_6", "TAXI_74", "TAXI_71" },
            { "TAXI_16", "TAXI_7", "TAXI_6", "TAXI_74" },
        },
    },
    {
        found = { "TAXI_2", "TAXI_6", "TAXI_7", "TAXI_4", "TAXI_12", "TAXI_5", "TAXI_71", "TAXI_74", "TAXI_8", "TAXI_16", "TAXI_14" },
        routes = {
            { "TAXI_14", "TAXI_7", "TAXI_6", "TAXI_2" },
            { "TAXI_14", "TAXI_7", "TAXI_6", "TAXI_2", "TAXI_4" },
            { "TAXI_14", "TAXI_7", "TAXI_6", "TAXI_74", "TAXI_71", "TAXI_5" },
            { "TAXI_14", "TAXI_6" },
            { "TAXI_14", "TAXI_7" },
            { "TAXI_14", "TAXI_16", "TAXI_8" },
            { "TAXI_14", "TAXI_7", "TAXI_6", "TAXI_74", "TAXI_71", "TAXI_5", "TAXI_12" },
            { "TAXI_14", "TAXI_16" },
            { "TAXI_14", "TAXI_7", "TAXI_6", "TAXI_74", "TAXI_71" },
            { "TAXI_14", "TAXI_7", "TAXI_6", "TAXI_74" },
        },
    },
}

local ali = makeCtx({ faction = "Alliance" })
local checked, wrong = 0, 0
for _, block in ipairs(blocks) do
    local found = {}
    for _, id in ipairs(block.found) do found[id] = true end
    ali.flightNodeFound = function(id) return found[id] == true end
    local graph = addon.TravelGraph:Build(ali)
    local flightsOnly = { adjacency = {}, anywhere = {} }              -- the game's routes are flights
    for id, steps in pairs(graph.adjacency) do
        for _, step in ipairs(steps) do
            if step.method == "flight" then
                flightsOnly.adjacency[id] = flightsOnly.adjacency[id] or {}
                table.insert(flightsOnly.adjacency[id], step)
            end
        end
    end
    for _, stops in ipairs(block.routes) do
        local result = addon.Pathfinder:FindPath(flightsOnly, stops[1], stops[#stops], nil, { oneTicket = true })
        local ours = { stops[1] }
        for _, step in ipairs(result and result.steps or {}) do ours[#ours + 1] = step.to end
        checked = checked + 1
        if table.concat(ours, ">") ~= table.concat(stops, ">") then
            wrong = wrong + 1
            check(false, "the game flew " .. table.concat(stops, ">") .. " but we plan " .. table.concat(ours, ">"))
        end
    end
end
check(checked > 40, "the captured routes were checked: " .. checked)
check(wrong == 0, "the planner picks the game's route every time")
