-- Borders.lua (Forever) -- GENERATED by tools/gen_borders.py from
-- tools/border_checklist.md (edit that and regenerate; hand edits here are lost).
--
-- Zone-to-zone walking crossings. Each is a pair of nodes, one just inside each
-- zone, joined by a walk edge. Coordinates were read off the in-game world map, so
-- they are rough: refine by walking a crossing and capturing `/mzdump here`.
-- A crossing with no `cost` has real travel inside it (a tunnel); the engine works
-- the cost out from the distance between its two ends.
--
-- Checked and NOT walkable (left out on purpose):
--   Elwynn Forest <-> Duskwood: Technically you can just swim across the southern river into Duskwood, but there's no "road" crossing
--   Redridge Mountains <-> Burning Steppes: Doesn't Exist...it's part of Riverglades now
--   Dun Morogh <-> Wetlands: Does Not Exist
--
-- Zones that touch on the map but have no crossing (no walkable link found):
-- kalimdor:
--    33 cells  Darkshore <-> Felwood
--    22 cells  Dustwallow Marsh <-> Thousand Needles
--    20 cells  Felwood <-> Mount Hyjal
--    19 cells  Desolace <-> Mulgore
--    16 cells  Azshara <-> Winterspring
--    15 cells  Feralas <-> Silithus
--    13 cells  Darkshore <-> Moonglade
--    11 cells  Feralas <-> Shen'dralas
--    10 cells  Feralas <-> Mulgore
--     8 cells  Mulgore <-> Shen'dralas
--     7 cells  Mulgore <-> Stonetalon Mountains
--     3 cells  Thousand Needles <-> Un'Goro Crater
--     2 cells  Ashenvale <-> Durotar
-- easternkingdoms:
--    21 cells  Eastern Plaguelands <-> The Hinterlands
--    20 cells  Dun Morogh <-> Wetlands
--    20 cells  Duskwood <-> Elwynn Forest
--    17 cells  Burning Steppes <-> Elwynn Forest
--    15 cells  Alterac Mountains <-> Silverpine Forest
--    14 cells  Dun Morogh <-> Searing Gorge
--     9 cells  Stranglethorn Vale <-> Westfall
--     9 cells  Blasted Lands <-> Stranglethorn Vale
--     7 cells  Alterac Mountains <-> The Hinterlands
--     7 cells  Blasted Lands <-> Deadwind Pass
--     6 cells  Badlands <-> Burning Steppes
--     4 cells  Burning Steppes <-> Redridge Mountains
--     3 cells  Alterac Mountains <-> Tirisfal Glades
--     3 cells  Hillsbrad Foothills <-> The Hinterlands
--     3 cells  Redridge Mountains <-> Swamp of Sorrows
--     1 cells  Deadwind Pass <-> Stranglethorn Vale

local addonName, addon = ...

addon.Nodes = addon.Nodes or {}
addon.Edges = addon.Edges or {}

addon.Nodes.Borders = {
    { id = "BORDER_DUROTAR_TO_THE_BARRENS", container = "kalimdor.durotar", mapID = 1411, x = 0.3490, y = 0.0430 }, -- Durotar side of the Durotar/The Barrens crossing
    { id = "BORDER_THE_BARRENS_TO_DUROTAR", container = "kalimdor.the_barrens", mapID = 1413, x = 0.6230, y = 0.1870 }, -- The Barrens side of the The Barrens/Durotar crossing
    { id = "BORDER_MULGORE_TO_THE_BARRENS", container = "kalimdor.mulgore", mapID = 1412, x = 0.6720, y = 0.6210 }, -- Mulgore side of the Mulgore/The Barrens crossing
    { id = "BORDER_THE_BARRENS_TO_MULGORE", container = "kalimdor.the_barrens", mapID = 1413, x = 0.4180, y = 0.5890 }, -- The Barrens side of the The Barrens/Mulgore crossing
    { id = "BORDER_THE_BARRENS_TO_STONETALON_MOUNTAINS", container = "kalimdor.the_barrens", mapID = 1413, x = 0.3620, y = 0.2780 }, -- The Barrens side of the The Barrens/Stonetalon Mountains crossing
    { id = "BORDER_STONETALON_MOUNTAINS_TO_THE_BARRENS", container = "kalimdor.stonetalon_mountains", mapID = 1442, x = 0.8760, y = 0.9610 }, -- Stonetalon Mountains side of the Stonetalon Mountains/The Barrens crossing
    { id = "BORDER_THE_BARRENS_TO_ASHENVALE", container = "kalimdor.the_barrens", mapID = 1413, x = 0.4820, y = 0.1030 }, -- The Barrens side of the The Barrens/Ashenvale crossing
    { id = "BORDER_ASHENVALE_TO_THE_BARRENS", container = "kalimdor.ashenvale", mapID = 1440, x = 0.6800, y = 0.8850 }, -- Ashenvale side of the Ashenvale/The Barrens crossing
    { id = "BORDER_THE_BARRENS_TO_THOUSAND_NEEDLES", container = "kalimdor.the_barrens", mapID = 1413, x = 0.4200, y = 0.9450 }, -- The Barrens side of the The Barrens/Thousand Needles crossing
    { id = "BORDER_THOUSAND_NEEDLES_TO_THE_BARRENS", container = "kalimdor.thousand_needles", mapID = 1441, x = 0.3190, y = 0.2230 }, -- Thousand Needles side of the Thousand Needles/The Barrens crossing
    { id = "BORDER_THE_BARRENS_TO_DUSTWALLOW_MARSH", container = "kalimdor.the_barrens", mapID = 1413, x = 0.5150, y = 0.7930 }, -- The Barrens side of the The Barrens/Dustwallow Marsh crossing
    { id = "BORDER_DUSTWALLOW_MARSH_TO_THE_BARRENS", container = "kalimdor.dustwallow_marsh", mapID = 1445, x = 0.3200, y = 0.4630 }, -- Dustwallow Marsh side of the Dustwallow Marsh/The Barrens crossing
    { id = "BORDER_ASHENVALE_TO_STONETALON_MOUNTAINS", container = "kalimdor.ashenvale", mapID = 1440, x = 0.4240, y = 0.7250 }, -- Ashenvale side of the Ashenvale/Stonetalon Mountains crossing
    { id = "BORDER_STONETALON_MOUNTAINS_TO_ASHENVALE", container = "kalimdor.stonetalon_mountains", mapID = 1442, x = 0.7790, y = 0.4150 }, -- Stonetalon Mountains side of the Stonetalon Mountains/Ashenvale crossing
    { id = "BORDER_ASHENVALE_TO_DARKSHORE", container = "kalimdor.ashenvale", mapID = 1440, x = 0.2800, y = 0.1280 }, -- Ashenvale side of the Ashenvale/Darkshore crossing
    { id = "BORDER_DARKSHORE_TO_ASHENVALE", container = "kalimdor.darkshore", mapID = 1439, x = 0.3710, y = 1.0000 }, -- Darkshore side of the Darkshore/Ashenvale crossing
    { id = "BORDER_ASHENVALE_TO_FELWOOD", container = "kalimdor.ashenvale", mapID = 1440, x = 0.5590, y = 0.2680 }, -- Ashenvale side of the Ashenvale/Felwood crossing
    { id = "BORDER_FELWOOD_TO_ASHENVALE", container = "kalimdor.felwood", mapID = 1448, x = 0.5700, y = 0.9850 }, -- Felwood side of the Felwood/Ashenvale crossing
    { id = "BORDER_ASHENVALE_TO_AZSHARA", container = "kalimdor.ashenvale", mapID = 1440, x = 0.9450, y = 0.4740 }, -- Ashenvale side of the Ashenvale/Azshara crossing
    { id = "BORDER_AZSHARA_TO_ASHENVALE", container = "kalimdor.azshara", mapID = 1447, x = 0.1040, y = 0.7450 }, -- Azshara side of the Azshara/Ashenvale crossing
    { id = "BORDER_FELWOOD_TO_WINTERSPRING", container = "kalimdor.felwood", mapID = 1448, x = 0.6540, y = 0.0690 }, -- Felwood side of the Felwood/Winterspring crossing
    { id = "BORDER_WINTERSPRING_TO_FELWOOD", container = "kalimdor.winterspring", mapID = 1452, x = 0.3050, y = 0.3540 }, -- Winterspring side of the Winterspring/Felwood crossing
    { id = "BORDER_FELWOOD_TO_MOONGLADE", container = "kalimdor.felwood", mapID = 1448, x = 0.6540, y = 0.0690 }, -- Felwood side of the Felwood/Moonglade crossing
    { id = "BORDER_MOONGLADE_TO_FELWOOD", container = "kalimdor.moonglade", mapID = 1450, x = 0.3540, y = 0.7360 }, -- Moonglade side of the Moonglade/Felwood crossing
    { id = "BORDER_WINTERSPRING_TO_MOONGLADE", container = "kalimdor.winterspring", mapID = 1452, x = 0.3050, y = 0.3540 }, -- Winterspring side of the Winterspring/Moonglade crossing
    { id = "BORDER_MOONGLADE_TO_WINTERSPRING", container = "kalimdor.moonglade", mapID = 1450, x = 0.3540, y = 0.7360 }, -- Moonglade side of the Moonglade/Winterspring crossing
    { id = "BORDER_WINTERSPRING_TO_MOUNT_HYJAL", container = "kalimdor.winterspring", mapID = 1452, x = 0.5100, y = 0.9130 }, -- Winterspring side of the Winterspring/Mount Hyjal crossing
    { id = "BORDER_MOUNT_HYJAL_TO_WINTERSPRING", container = "kalimdor.mount_hyjal", mapID = 2482, x = 0.8790, y = 0.3700 }, -- Mount Hyjal side of the Mount Hyjal/Winterspring crossing
    { id = "BORDER_STONETALON_MOUNTAINS_TO_DESOLACE", container = "kalimdor.stonetalon_mountains", mapID = 1442, x = 0.2900, y = 0.8090 }, -- Stonetalon Mountains side of the Stonetalon Mountains/Desolace crossing
    { id = "BORDER_DESOLACE_TO_STONETALON_MOUNTAINS", container = "kalimdor.desolace", mapID = 1443, x = 0.5340, y = 0.0570 }, -- Desolace side of the Desolace/Stonetalon Mountains crossing
    { id = "BORDER_DESOLACE_TO_FERALAS", container = "kalimdor.desolace", mapID = 1443, x = 0.4280, y = 0.9790 }, -- Desolace side of the Desolace/Feralas crossing
    { id = "BORDER_FERALAS_TO_DESOLACE", container = "kalimdor.feralas", mapID = 1444, x = 0.4610, y = 0.0400 }, -- Feralas side of the Feralas/Desolace crossing
    { id = "BORDER_DESOLACE_TO_SHENDRALAS", container = "kalimdor.desolace", mapID = 1443, x = 0.6800, y = 0.8810 }, -- Desolace side of the Desolace/Shen'dralas crossing
    { id = "BORDER_SHENDRALAS_TO_DESOLACE", container = "kalimdor.shendralas", mapID = 2652, x = 0.3390, y = 0.0760 }, -- Shen'dralas side of the Shen'dralas/Desolace crossing
    { id = "BORDER_DESOLACE_TO_SHENDRALAS_2", container = "kalimdor.desolace", mapID = 1443, x = 0.5860, y = 0.9010 }, -- Desolace side of the Desolace/Shen'dralas crossing
    { id = "BORDER_SHENDRALAS_TO_DESOLACE_2", container = "kalimdor.shendralas", mapID = 2652, x = 0.2240, y = 0.2410 }, -- Shen'dralas side of the Shen'dralas/Desolace crossing
    { id = "BORDER_THOUSAND_NEEDLES_TO_TANARIS", container = "kalimdor.thousand_needles", mapID = 1441, x = 0.7500, y = 0.9580 }, -- Thousand Needles side of the Thousand Needles/Tanaris crossing
    { id = "BORDER_TANARIS_TO_THOUSAND_NEEDLES", container = "kalimdor.tanaris", mapID = 1446, x = 0.5070, y = 0.2250 }, -- Tanaris side of the Tanaris/Thousand Needles crossing
    { id = "BORDER_THOUSAND_NEEDLES_TO_FERALAS", container = "kalimdor.thousand_needles", mapID = 1441, x = 0.0660, y = 0.1350 }, -- Thousand Needles side of the Thousand Needles/Feralas crossing
    { id = "BORDER_FERALAS_TO_THOUSAND_NEEDLES", container = "kalimdor.feralas", mapID = 1444, x = 0.9670, y = 0.4830 }, -- Feralas side of the Feralas/Thousand Needles crossing
    { id = "BORDER_TANARIS_TO_UNGORO_CRATER", container = "kalimdor.tanaris", mapID = 1446, x = 0.2680, y = 0.5310 }, -- Tanaris side of the Tanaris/Un'Goro Crater crossing
    { id = "BORDER_UNGORO_CRATER_TO_TANARIS", container = "kalimdor.ungoro_crater", mapID = 1449, x = 0.6750, y = 0.8150 }, -- Un'Goro Crater side of the Un'Goro Crater/Tanaris crossing
    { id = "BORDER_UNGORO_CRATER_TO_SILITHUS", container = "kalimdor.ungoro_crater", mapID = 1449, x = 0.3470, y = 0.1690 }, -- Un'Goro Crater side of the Un'Goro Crater/Silithus crossing
    { id = "BORDER_SILITHUS_TO_UNGORO_CRATER", container = "kalimdor.silithus", mapID = 1451, x = 0.8130, y = 0.1650 }, -- Silithus side of the Silithus/Un'Goro Crater crossing
    { id = "BORDER_ELWYNN_FOREST_TO_WESTFALL", container = "easternkingdoms.elwynn_forest", mapID = 1429, x = 0.2060, y = 0.7980 }, -- Elwynn Forest side of the Elwynn Forest/Westfall crossing
    { id = "BORDER_WESTFALL_TO_ELWYNN_FOREST", container = "easternkingdoms.westfall", mapID = 1436, x = 0.6160, y = 0.1800 }, -- Westfall side of the Westfall/Elwynn Forest crossing
    { id = "BORDER_ELWYNN_FOREST_TO_REDRIDGE_MOUNTAINS", container = "easternkingdoms.elwynn_forest", mapID = 1429, x = 0.9380, y = 0.7210 }, -- Elwynn Forest side of the Elwynn Forest/Redridge Mountains crossing
    { id = "BORDER_REDRIDGE_MOUNTAINS_TO_ELWYNN_FOREST", container = "easternkingdoms.redridge_mountains", mapID = 1433, x = 0.0280, y = 0.7280 }, -- Redridge Mountains side of the Redridge Mountains/Elwynn Forest crossing
    { id = "BORDER_DUSKWOOD_TO_WESTFALL", container = "easternkingdoms.duskwood", mapID = 1431, x = 0.0870, y = 0.6350 }, -- Duskwood side of the Duskwood/Westfall crossing
    { id = "BORDER_WESTFALL_TO_DUSKWOOD", container = "easternkingdoms.westfall", mapID = 1436, x = 0.6720, y = 0.6240 }, -- Westfall side of the Westfall/Duskwood crossing
    { id = "BORDER_DUSKWOOD_TO_REDRIDGE_MOUNTAINS", container = "easternkingdoms.duskwood", mapID = 1431, x = 0.9340, y = 0.1080 }, -- Duskwood side of the Duskwood/Redridge Mountains crossing
    { id = "BORDER_REDRIDGE_MOUNTAINS_TO_DUSKWOOD", container = "easternkingdoms.redridge_mountains", mapID = 1433, x = 0.0770, y = 0.8830 }, -- Redridge Mountains side of the Redridge Mountains/Duskwood crossing
    { id = "BORDER_DUSKWOOD_TO_STRANGLETHORN_VALE", container = "easternkingdoms.duskwood", mapID = 1431, x = 0.4440, y = 0.9770 }, -- Duskwood side of the Duskwood/Stranglethorn Vale crossing
    { id = "BORDER_STRANGLETHORN_VALE_TO_DUSKWOOD", container = "easternkingdoms.stranglethorn_vale", mapID = 1434, x = 0.3960, y = 0.0430 }, -- Stranglethorn Vale side of the Stranglethorn Vale/Duskwood crossing
    { id = "BORDER_DUSKWOOD_TO_DEADWIND_PASS", container = "easternkingdoms.duskwood", mapID = 1431, x = 0.8980, y = 0.4000 }, -- Duskwood side of the Duskwood/Deadwind Pass crossing
    { id = "BORDER_DEADWIND_PASS_TO_DUSKWOOD", container = "easternkingdoms.deadwind_pass", mapID = 1430, x = 0.3190, y = 0.3480 }, -- Deadwind Pass side of the Deadwind Pass/Duskwood crossing
    { id = "BORDER_DEADWIND_PASS_TO_SWAMP_OF_SORROWS", container = "easternkingdoms.deadwind_pass", mapID = 1430, x = 0.5910, y = 0.4160 }, -- Deadwind Pass side of the Deadwind Pass/Swamp of Sorrows crossing
    { id = "BORDER_SWAMP_OF_SORROWS_TO_DEADWIND_PASS", container = "easternkingdoms.swamp_of_sorrows", mapID = 1435, x = 0.0290, y = 0.6070 }, -- Swamp of Sorrows side of the Swamp of Sorrows/Deadwind Pass crossing
    { id = "BORDER_SWAMP_OF_SORROWS_TO_BLASTED_LANDS", container = "easternkingdoms.swamp_of_sorrows", mapID = 1435, x = 0.3330, y = 0.7410 }, -- Swamp of Sorrows side of the Swamp of Sorrows/Blasted Lands crossing
    { id = "BORDER_BLASTED_LANDS_TO_SWAMP_OF_SORROWS", container = "easternkingdoms.blasted_lands", mapID = 1419, x = 0.5270, y = 0.0850 }, -- Blasted Lands side of the Blasted Lands/Swamp of Sorrows crossing
    { id = "BORDER_BURNING_STEPPES_TO_SEARING_GORGE", container = "easternkingdoms.burning_steppes", mapID = 1428, x = 0.2960, y = 0.3700 }, -- Burning Steppes side of the Burning Steppes/Searing Gorge crossing
    { id = "BORDER_SEARING_GORGE_TO_BURNING_STEPPES", container = "easternkingdoms.searing_gorge", mapID = 1427, x = 0.3690, y = 0.8380 }, -- Searing Gorge side of the Searing Gorge/Burning Steppes crossing
    { id = "BORDER_SEARING_GORGE_TO_BADLANDS", container = "easternkingdoms.searing_gorge", mapID = 1427, x = 0.7760, y = 0.6010 }, -- Searing Gorge side of the Searing Gorge/Badlands crossing
    { id = "BORDER_BADLANDS_TO_SEARING_GORGE", container = "easternkingdoms.badlands", mapID = 1418, x = 0.0870, y = 0.6800 }, -- Badlands side of the Badlands/Searing Gorge crossing
    { id = "BORDER_BADLANDS_TO_LOCH_MODAN", container = "easternkingdoms.badlands", mapID = 1418, x = 0.4670, y = 0.0360 }, -- Badlands side of the Badlands/Loch Modan crossing
    { id = "BORDER_LOCH_MODAN_TO_BADLANDS", container = "easternkingdoms.loch_modan", mapID = 1432, x = 0.4720, y = 0.8540 }, -- Loch Modan side of the Loch Modan/Badlands crossing
    { id = "BORDER_BADLANDS_TO_RIVERGLADES", container = "easternkingdoms.badlands", mapID = 1418, x = 0.6250, y = 0.8410 }, -- Badlands side of the Badlands/Riverglades crossing
    { id = "BORDER_RIVERGLADES_TO_BADLANDS", container = "easternkingdoms.riverglades", mapID = 2548, x = 0.3170, y = 0.2500 }, -- Riverglades side of the Riverglades/Badlands crossing
    { id = "BORDER_RIVERGLADES_TO_REDRIDGE_MOUNTAINS", container = "easternkingdoms.riverglades", mapID = 2548, x = 0.1380, y = 0.7840 }, -- Riverglades side of the Riverglades/Redridge Mountains crossing
    { id = "BORDER_REDRIDGE_MOUNTAINS_TO_RIVERGLADES", container = "easternkingdoms.redridge_mountains", mapID = 1433, x = 0.5230, y = 0.0760 }, -- Redridge Mountains side of the Redridge Mountains/Riverglades crossing
    { id = "BORDER_RIVERGLADES_TO_BURNING_STEPPES", container = "easternkingdoms.riverglades", mapID = 2548, x = 0.1380, y = 0.6480 }, -- Riverglades side of the Riverglades/Burning Steppes crossing
    { id = "BORDER_BURNING_STEPPES_TO_RIVERGLADES", container = "easternkingdoms.burning_steppes", mapID = 1428, x = 0.9450, y = 0.7030 }, -- Burning Steppes side of the Burning Steppes/Riverglades crossing
    { id = "BORDER_RIVERGLADES_TO_SWAMP_OF_SORROWS", container = "easternkingdoms.riverglades", mapID = 2548, x = 0.3690, y = 0.9190 }, -- Riverglades side of the Riverglades/Swamp of Sorrows crossing
    { id = "BORDER_SWAMP_OF_SORROWS_TO_RIVERGLADES", container = "easternkingdoms.swamp_of_sorrows", mapID = 1435, x = 0.6530, y = 0.1060 }, -- Swamp of Sorrows side of the Swamp of Sorrows/Riverglades crossing
    { id = "BORDER_LOCH_MODAN_TO_DUN_MOROGH", container = "easternkingdoms.loch_modan", mapID = 1432, x = 0.2040, y = 0.6330 }, -- Loch Modan side of the Loch Modan/Dun Morogh crossing
    { id = "BORDER_DUN_MOROGH_TO_LOCH_MODAN", container = "easternkingdoms.dun_morogh", mapID = 1426, x = 0.8470, y = 0.3050 }, -- Dun Morogh side of the Dun Morogh/Loch Modan crossing
    { id = "BORDER_LOCH_MODAN_TO_WETLANDS", container = "easternkingdoms.loch_modan", mapID = 1432, x = 0.2530, y = 0.0900 }, -- Loch Modan side of the Loch Modan/Wetlands crossing
    { id = "BORDER_WETLANDS_TO_LOCH_MODAN", container = "easternkingdoms.wetlands", mapID = 1437, x = 0.5370, y = 0.7280 }, -- Wetlands side of the Wetlands/Loch Modan crossing
    { id = "BORDER_LOCH_MODAN_TO_SEARING_GORGE", container = "easternkingdoms.loch_modan", mapID = 1432, x = 0.1680, y = 0.8400 }, -- Loch Modan side of the Loch Modan/Searing Gorge crossing
    { id = "BORDER_SEARING_GORGE_TO_LOCH_MODAN", container = "easternkingdoms.searing_gorge", mapID = 1427, x = 0.7840, y = 0.1670 }, -- Searing Gorge side of the Searing Gorge/Loch Modan crossing
    { id = "BORDER_WETLANDS_TO_ARATHI_HIGHLANDS", container = "easternkingdoms.wetlands", mapID = 1437, x = 0.5150, y = 0.0950 }, -- Wetlands side of the Wetlands/Arathi Highlands crossing
    { id = "BORDER_ARATHI_HIGHLANDS_TO_WETLANDS", container = "easternkingdoms.arathi_highlands", mapID = 1417, x = 0.4550, y = 0.9080 }, -- Arathi Highlands side of the Arathi Highlands/Wetlands crossing
    { id = "BORDER_ARATHI_HIGHLANDS_TO_HILLSBRAD_FOOTHILLS", container = "easternkingdoms.arathi_highlands", mapID = 1417, x = 0.1990, y = 0.3000 }, -- Arathi Highlands side of the Arathi Highlands/Hillsbrad Foothills crossing
    { id = "BORDER_HILLSBRAD_FOOTHILLS_TO_ARATHI_HIGHLANDS", container = "easternkingdoms.hillsbrad_foothills", mapID = 1424, x = 0.8170, y = 0.5600 }, -- Hillsbrad Foothills side of the Hillsbrad Foothills/Arathi Highlands crossing
    { id = "BORDER_ARATHI_HIGHLANDS_TO_HINTERLANDS", container = "easternkingdoms.arathi_highlands", mapID = 1417, x = 0.8680, y = 0.2870 }, -- Arathi Highlands side of the Arathi Highlands/The Hinterlands crossing
    { id = "BORDER_HINTERLANDS_TO_ARATHI_HIGHLANDS", container = "easternkingdoms.hinterlands", mapID = 1425, x = 0.0570, y = 0.6050 }, -- The Hinterlands side of the The Hinterlands/Arathi Highlands crossing
    { id = "BORDER_HILLSBRAD_FOOTHILLS_TO_SILVERPINE_FOREST", container = "easternkingdoms.hillsbrad_foothills", mapID = 1424, x = 0.0450, y = 0.4200 }, -- Hillsbrad Foothills side of the Hillsbrad Foothills/Silverpine Forest crossing
    { id = "BORDER_SILVERPINE_FOREST_TO_HILLSBRAD_FOOTHILLS", container = "easternkingdoms.silverpine_forest", mapID = 1421, x = 0.6760, y = 0.8070 }, -- Silverpine Forest side of the Silverpine Forest/Hillsbrad Foothills crossing
    { id = "BORDER_HILLSBRAD_FOOTHILLS_TO_ALTERAC_MOUNTAINS", container = "easternkingdoms.hillsbrad_foothills", mapID = 1424, x = 0.5370, y = 0.0810 }, -- Hillsbrad Foothills side of the Hillsbrad Foothills/Alterac Mountains crossing
    { id = "BORDER_ALTERAC_MOUNTAINS_TO_HILLSBRAD_FOOTHILLS", container = "easternkingdoms.alterac_mountains", mapID = 1416, x = 0.5360, y = 0.9330 }, -- Alterac Mountains side of the Alterac Mountains/Hillsbrad Foothills crossing
    { id = "BORDER_HINTERLANDS_TO_WESTERN_PLAGUELANDS", container = "easternkingdoms.hinterlands", mapID = 1425, x = 0.2360, y = 0.2620 }, -- The Hinterlands side of the The Hinterlands/Western Plaguelands crossing
    { id = "BORDER_WESTERN_PLAGUELANDS_TO_HINTERLANDS", container = "easternkingdoms.western_plaguelands", mapID = 1422, x = 0.6760, y = 0.8740 }, -- Western Plaguelands side of the Western Plaguelands/The Hinterlands crossing
    { id = "BORDER_ALTERAC_MOUNTAINS_TO_WESTERN_PLAGUELANDS", container = "easternkingdoms.alterac_mountains", mapID = 1416, x = 0.8020, y = 0.3090 }, -- Alterac Mountains side of the Alterac Mountains/Western Plaguelands crossing
    { id = "BORDER_WESTERN_PLAGUELANDS_TO_ALTERAC_MOUNTAINS", container = "easternkingdoms.western_plaguelands", mapID = 1422, x = 0.4320, y = 0.9380 }, -- Western Plaguelands side of the Western Plaguelands/Alterac Mountains crossing
    { id = "BORDER_SILVERPINE_FOREST_TO_TIRISFAL_GLADES", container = "easternkingdoms.silverpine_forest", mapID = 1421, x = 0.6810, y = 0.0430 }, -- Silverpine Forest side of the Silverpine Forest/Tirisfal Glades crossing
    { id = "BORDER_TIRISFAL_GLADES_TO_SILVERPINE_FOREST", container = "easternkingdoms.tirisfal_glades", mapID = 1420, x = 0.5100, y = 0.7360 }, -- Tirisfal Glades side of the Tirisfal Glades/Silverpine Forest crossing
    { id = "BORDER_TIRISFAL_GLADES_TO_WESTERN_PLAGUELANDS", container = "easternkingdoms.tirisfal_glades", mapID = 1420, x = 0.8510, y = 0.6980 }, -- Tirisfal Glades side of the Tirisfal Glades/Western Plaguelands crossing
    { id = "BORDER_WESTERN_PLAGUELANDS_TO_TIRISFAL_GLADES", container = "easternkingdoms.western_plaguelands", mapID = 1422, x = 0.2040, y = 0.5720 }, -- Western Plaguelands side of the Western Plaguelands/Tirisfal Glades crossing
    { id = "BORDER_WESTERN_PLAGUELANDS_TO_EASTERN_PLAGUELANDS", container = "easternkingdoms.western_plaguelands", mapID = 1422, x = 0.7550, y = 0.4990 }, -- Western Plaguelands side of the Western Plaguelands/Eastern Plaguelands crossing
    { id = "BORDER_EASTERN_PLAGUELANDS_TO_WESTERN_PLAGUELANDS", container = "easternkingdoms.eastern_plaguelands", mapID = 1423, x = 0.0940, y = 0.7250 }, -- Eastern Plaguelands side of the Eastern Plaguelands/Western Plaguelands crossing
}

for _, edge in ipairs({
    { from = "BORDER_DUROTAR_TO_THE_BARRENS", to = "BORDER_THE_BARRENS_TO_DUROTAR", method = "walk", cost = 0 }, -- Durotar <-> The Barrens
    { from = "BORDER_MULGORE_TO_THE_BARRENS", to = "BORDER_THE_BARRENS_TO_MULGORE", method = "walk", cost = 0 }, -- Mulgore <-> The Barrens
    { from = "BORDER_THE_BARRENS_TO_STONETALON_MOUNTAINS", to = "BORDER_STONETALON_MOUNTAINS_TO_THE_BARRENS", method = "walk", cost = 0 }, -- The Barrens <-> Stonetalon Mountains
    { from = "BORDER_THE_BARRENS_TO_ASHENVALE", to = "BORDER_ASHENVALE_TO_THE_BARRENS", method = "walk", cost = 0 }, -- The Barrens <-> Ashenvale
    { from = "BORDER_THE_BARRENS_TO_THOUSAND_NEEDLES", to = "BORDER_THOUSAND_NEEDLES_TO_THE_BARRENS", method = "walk", cost = 0 }, -- The Barrens <-> Thousand Needles
    { from = "BORDER_THE_BARRENS_TO_DUSTWALLOW_MARSH", to = "BORDER_DUSTWALLOW_MARSH_TO_THE_BARRENS", method = "walk", cost = 0 }, -- The Barrens <-> Dustwallow Marsh
    { from = "BORDER_ASHENVALE_TO_STONETALON_MOUNTAINS", to = "BORDER_STONETALON_MOUNTAINS_TO_ASHENVALE", method = "walk" }, -- Ashenvale <-> Stonetalon Mountains (via Talondeep Path tunnel (not zero travel))
    { from = "BORDER_ASHENVALE_TO_DARKSHORE", to = "BORDER_DARKSHORE_TO_ASHENVALE", method = "walk", cost = 0 }, -- Ashenvale <-> Darkshore
    { from = "BORDER_ASHENVALE_TO_FELWOOD", to = "BORDER_FELWOOD_TO_ASHENVALE", method = "walk", cost = 0 }, -- Ashenvale <-> Felwood
    { from = "BORDER_ASHENVALE_TO_AZSHARA", to = "BORDER_AZSHARA_TO_ASHENVALE", method = "walk", cost = 0 }, -- Ashenvale <-> Azshara
    { from = "BORDER_FELWOOD_TO_WINTERSPRING", to = "BORDER_WINTERSPRING_TO_FELWOOD", method = "walk" }, -- Felwood <-> Winterspring (via Timbermaw Hold tunnel (not zero travel))
    { from = "BORDER_FELWOOD_TO_MOONGLADE", to = "BORDER_MOONGLADE_TO_FELWOOD", method = "walk" }, -- Felwood <-> Moonglade (via Timbermaw Hold tunnel (not zero travel))
    { from = "BORDER_WINTERSPRING_TO_MOONGLADE", to = "BORDER_MOONGLADE_TO_WINTERSPRING", method = "walk" }, -- Winterspring <-> Moonglade (via Timbermaw Hold tunnel (not zero travel))
    { from = "BORDER_WINTERSPRING_TO_MOUNT_HYJAL", to = "BORDER_MOUNT_HYJAL_TO_WINTERSPRING", method = "walk", cost = 0 }, -- Winterspring <-> Mount Hyjal
    { from = "BORDER_STONETALON_MOUNTAINS_TO_DESOLACE", to = "BORDER_DESOLACE_TO_STONETALON_MOUNTAINS", method = "walk", cost = 0 }, -- Stonetalon Mountains <-> Desolace
    { from = "BORDER_DESOLACE_TO_FERALAS", to = "BORDER_FERALAS_TO_DESOLACE", method = "walk", cost = 0 }, -- Desolace <-> Feralas
    { from = "BORDER_DESOLACE_TO_SHENDRALAS", to = "BORDER_SHENDRALAS_TO_DESOLACE", method = "walk", cost = 0 }, -- Desolace <-> Shen'dralas
    { from = "BORDER_DESOLACE_TO_SHENDRALAS_2", to = "BORDER_SHENDRALAS_TO_DESOLACE_2", method = "walk", cost = 0 }, -- Desolace <-> Shen'dralas
    { from = "BORDER_THOUSAND_NEEDLES_TO_TANARIS", to = "BORDER_TANARIS_TO_THOUSAND_NEEDLES", method = "walk", cost = 0 }, -- Thousand Needles <-> Tanaris
    { from = "BORDER_THOUSAND_NEEDLES_TO_FERALAS", to = "BORDER_FERALAS_TO_THOUSAND_NEEDLES", method = "walk", cost = 0 }, -- Thousand Needles <-> Feralas
    { from = "BORDER_TANARIS_TO_UNGORO_CRATER", to = "BORDER_UNGORO_CRATER_TO_TANARIS", method = "walk", cost = 0 }, -- Tanaris <-> Un'Goro Crater
    { from = "BORDER_UNGORO_CRATER_TO_SILITHUS", to = "BORDER_SILITHUS_TO_UNGORO_CRATER", method = "walk", cost = 0 }, -- Un'Goro Crater <-> Silithus
    { from = "BORDER_ELWYNN_FOREST_TO_WESTFALL", to = "BORDER_WESTFALL_TO_ELWYNN_FOREST", method = "walk", cost = 0 }, -- Elwynn Forest <-> Westfall
    { from = "BORDER_ELWYNN_FOREST_TO_REDRIDGE_MOUNTAINS", to = "BORDER_REDRIDGE_MOUNTAINS_TO_ELWYNN_FOREST", method = "walk", cost = 0 }, -- Elwynn Forest <-> Redridge Mountains
    { from = "BORDER_DUSKWOOD_TO_WESTFALL", to = "BORDER_WESTFALL_TO_DUSKWOOD", method = "walk", cost = 0 }, -- Duskwood <-> Westfall
    { from = "BORDER_DUSKWOOD_TO_REDRIDGE_MOUNTAINS", to = "BORDER_REDRIDGE_MOUNTAINS_TO_DUSKWOOD", method = "walk", cost = 0 }, -- Duskwood <-> Redridge Mountains
    { from = "BORDER_DUSKWOOD_TO_STRANGLETHORN_VALE", to = "BORDER_STRANGLETHORN_VALE_TO_DUSKWOOD", method = "walk", cost = 0 }, -- Duskwood <-> Stranglethorn Vale
    { from = "BORDER_DUSKWOOD_TO_DEADWIND_PASS", to = "BORDER_DEADWIND_PASS_TO_DUSKWOOD", method = "walk", cost = 0 }, -- Duskwood <-> Deadwind Pass
    { from = "BORDER_DEADWIND_PASS_TO_SWAMP_OF_SORROWS", to = "BORDER_SWAMP_OF_SORROWS_TO_DEADWIND_PASS", method = "walk", cost = 0 }, -- Deadwind Pass <-> Swamp of Sorrows
    { from = "BORDER_SWAMP_OF_SORROWS_TO_BLASTED_LANDS", to = "BORDER_BLASTED_LANDS_TO_SWAMP_OF_SORROWS", method = "walk", cost = 0 }, -- Swamp of Sorrows <-> Blasted Lands
    { from = "BORDER_BURNING_STEPPES_TO_SEARING_GORGE", to = "BORDER_SEARING_GORGE_TO_BURNING_STEPPES", method = "walk" }, -- Burning Steppes <-> Searing Gorge (via Blackrock Mountain (not zero travel))
    { from = "BORDER_SEARING_GORGE_TO_BADLANDS", to = "BORDER_BADLANDS_TO_SEARING_GORGE", method = "walk", cost = 0 }, -- Searing Gorge <-> Badlands
    { from = "BORDER_BADLANDS_TO_LOCH_MODAN", to = "BORDER_LOCH_MODAN_TO_BADLANDS", method = "walk", cost = 0 }, -- Badlands <-> Loch Modan
    { from = "BORDER_BADLANDS_TO_RIVERGLADES", to = "BORDER_RIVERGLADES_TO_BADLANDS", method = "walk", cost = 0 }, -- Badlands <-> Riverglades
    { from = "BORDER_RIVERGLADES_TO_REDRIDGE_MOUNTAINS", to = "BORDER_REDRIDGE_MOUNTAINS_TO_RIVERGLADES", method = "walk", cost = 0 }, -- Riverglades <-> Redridge Mountains
    { from = "BORDER_RIVERGLADES_TO_BURNING_STEPPES", to = "BORDER_BURNING_STEPPES_TO_RIVERGLADES", method = "walk", cost = 0 }, -- Riverglades <-> Burning Steppes
    { from = "BORDER_RIVERGLADES_TO_SWAMP_OF_SORROWS", to = "BORDER_SWAMP_OF_SORROWS_TO_RIVERGLADES", method = "walk", cost = 0 }, -- Riverglades <-> Swamp of Sorrows
    { from = "BORDER_LOCH_MODAN_TO_DUN_MOROGH", to = "BORDER_DUN_MOROGH_TO_LOCH_MODAN", method = "walk", cost = 0 }, -- Loch Modan <-> Dun Morogh
    { from = "BORDER_LOCH_MODAN_TO_WETLANDS", to = "BORDER_WETLANDS_TO_LOCH_MODAN", method = "walk", cost = 0 }, -- Loch Modan <-> Wetlands
    { from = "BORDER_LOCH_MODAN_TO_SEARING_GORGE", to = "BORDER_SEARING_GORGE_TO_LOCH_MODAN", method = "walk", requirements = { quest = 3201 } }, -- Loch Modan <-> Searing Gorge (Via Stonewrought Pass, needs a key; requires quest 3201 ("At Last!" rewards the Key to Searing Gorge, item 5396); not zero travel)
    { from = "BORDER_WETLANDS_TO_ARATHI_HIGHLANDS", to = "BORDER_ARATHI_HIGHLANDS_TO_WETLANDS", method = "walk", cost = 0 }, -- Wetlands <-> Arathi Highlands
    { from = "BORDER_ARATHI_HIGHLANDS_TO_HILLSBRAD_FOOTHILLS", to = "BORDER_HILLSBRAD_FOOTHILLS_TO_ARATHI_HIGHLANDS", method = "walk", cost = 0 }, -- Arathi Highlands <-> Hillsbrad Foothills
    { from = "BORDER_ARATHI_HIGHLANDS_TO_HINTERLANDS", to = "BORDER_HINTERLANDS_TO_ARATHI_HIGHLANDS", method = "walk", cost = 0 }, -- Arathi Highlands <-> The Hinterlands
    { from = "BORDER_HILLSBRAD_FOOTHILLS_TO_SILVERPINE_FOREST", to = "BORDER_SILVERPINE_FOREST_TO_HILLSBRAD_FOOTHILLS", method = "walk", cost = 0 }, -- Hillsbrad Foothills <-> Silverpine Forest
    { from = "BORDER_HILLSBRAD_FOOTHILLS_TO_ALTERAC_MOUNTAINS", to = "BORDER_ALTERAC_MOUNTAINS_TO_HILLSBRAD_FOOTHILLS", method = "walk", cost = 0 }, -- Hillsbrad Foothills <-> Alterac Mountains
    { from = "BORDER_HINTERLANDS_TO_WESTERN_PLAGUELANDS", to = "BORDER_WESTERN_PLAGUELANDS_TO_HINTERLANDS", method = "walk", cost = 0 }, -- The Hinterlands <-> Western Plaguelands
    { from = "BORDER_ALTERAC_MOUNTAINS_TO_WESTERN_PLAGUELANDS", to = "BORDER_WESTERN_PLAGUELANDS_TO_ALTERAC_MOUNTAINS", method = "walk", cost = 0 }, -- Alterac Mountains <-> Western Plaguelands
    { from = "BORDER_SILVERPINE_FOREST_TO_TIRISFAL_GLADES", to = "BORDER_TIRISFAL_GLADES_TO_SILVERPINE_FOREST", method = "walk", cost = 0 }, -- Silverpine Forest <-> Tirisfal Glades
    { from = "BORDER_TIRISFAL_GLADES_TO_WESTERN_PLAGUELANDS", to = "BORDER_WESTERN_PLAGUELANDS_TO_TIRISFAL_GLADES", method = "walk", cost = 0 }, -- Tirisfal Glades <-> Western Plaguelands
    { from = "BORDER_WESTERN_PLAGUELANDS_TO_EASTERN_PLAGUELANDS", to = "BORDER_EASTERN_PLAGUELANDS_TO_WESTERN_PLAGUELANDS", method = "walk", cost = 0 }, -- Western Plaguelands <-> Eastern Plaguelands
}) do
    table.insert(addon.Edges, edge)
end
