-- Edges.lua (Forever)
--
-- Everything that isn't a classic flight: ships, zeppelins, the tram, portals, druid flights and
-- the placeholders for new Forever-only flights.
--
-- The classic flight network is in Flights.lua, generated by tools/gen_flights.py as SINGLE LEGS
-- (a flight master to the next one along the route). It used to be here as whole tickets timed by
-- InFlight's crowd, but a ticket flies through other flight points, and which ones depends on which
-- points the flyer had found, so its time can't be trusted for a player with a different set. The
-- original ticket times are kept in tools/flight_source/inflight_tickets.lua.

local addonName, addon = ...

addon.Edges = addon.Edges or {}

-----------------------------------------------------------
-- New Forever-only content — no classic precedent exists in InFlight's
-- data, so these remain last night's distance-based placeholder, NOT
-- sourced from real data. Faction ownership unverified; left unset
-- (usable by anyone) rather than guessed.
-----------------------------------------------------------

for _, edge in ipairs({
    { from = "TAXI_44", to = "TAXI_3242", cost = 172 }, -- Valormok -> Tainted Foothills
    { from = "TAXI_61", to = "TAXI_3242", cost = 211 }, -- Splintertree Post -> Tainted Foothills
    { from = "TAXI_559", to = "TAXI_3242", cost = 101 }, -- Summit of Eternity -> Tainted Foothills
    -- Faction split learned live from the Alliance flight map at Ironforge (/mzslots):
    -- it lists Farholde Keep and Morgan's Vigil but NOT Rog'mar, Stonard or Flame
    -- Crest. So the distance-based placeholders that crossed factions
    -- (Rog'mar<->Farholde, Rog'mar->Morgan's Vigil, Farholde->Stonard) were dropped.
    -- Rog'mar being Horde-only is inferred from its absence there; not yet
    -- confirmed on a Horde slot list.
    { from = "TAXI_3203", to = "TAXI_70", cost = 263, requirements = { faction = "Horde" } }, -- Rog'mar -> Flame Crest
    { from = "TAXI_3276", to = "TAXI_71", cost = 222, requirements = { faction = "Alliance" } }, -- Farholde Keep -> Morgan's Vigil
}) do
    edge.method = "taxi"
    table.insert(addon.Edges, edge)
end

-----------------------------------------------------------
-- Druid dialog flights
--
-- The Nighthaven (Moonglade) flight masters are druid-only and NOT taxi-map
-- nodes: talking to one offers a dialog option that flies you straight to a
-- destination, so each is a single one-way edge with no return trip.
-- Faction-locked. The Darnassus one was ridden live: lands exactly on the
-- Rut'theran Village flight master (TAXI_27), 154s, no loading screen. The
-- Thunder Bluff one (TAXI_63) has not been visited, so its cost is an
-- ESTIMATE: the regular Moonglade -> Thunder Bluff flight is 532s in
-- InFlight's data vs 226s for Moonglade -> Rut'theran, and the measured druid
-- flight to Rut'theran is 154s (ratio ~0.68), so ~362s. Faction is Horde by
-- assumption (druid flights are faction-locked and it flies to Thunder Bluff).
-----------------------------------------------------------

table.insert(addon.Edges, {
    from = "TAXI_63", to = "TAXI_22", method = "taxi", cost = 362, loadingScreens = 0, oneway = true,
    requirements = { faction = "Horde", class = "DRUID" },
}) -- Nighthaven (Moonglade) -> Thunder Bluff, ESTIMATED, not ridden

table.insert(addon.Edges, {
    from = "TAXI_62", to = "TAXI_27", method = "taxi", cost = 154, loadingScreens = 0, oneway = true,
    requirements = { faction = "Alliance", class = "DRUID" },
}) -- Nighthaven (Moonglade) -> Rut'theran Village, MEASURED live

-----------------------------------------------------------
-- Boats, zeppelins, tram
--
-- Sourced from the Atlas site's "Travel" tab (real routes with real
-- endpoints), not InFlight -- that data has no timing for these at all, so
-- ship/tram costs below are still PLACEHOLDER round numbers, not measured.
-- Orgrimmar<->Grom'gol zeppelin is now a real live measurement: 60s
-- dock/board window + 60s transit each way (120s used as a flat estimate;
-- real wait depends on arrival timing relative to the boarding window).
-- The other two zeppelin legs reuse that number as an estimate, not
-- independently timed yet. VERIFY IN-GAME for anything not called out here.
--
-- The Menethil-Southshore-Auberdine "new" line's stop order wasn't detailed
-- by the site ("Stop order and direction are not detailed yet"); it has since
-- been ridden and timed live and turned out to be a one-way three-stop loop
-- (see the block below).
--
-- Shuttle-boat costs use the average 2T + D (T = transit, D = dock time);
-- loops use C/2 + ride time. Both exclude loading tax.
--
-- Deeprun Tram now uses real exterior-entrance nodes (TRAM_STORMWIND /
-- TRAM_IRONFORGE), captured live; see the edge below.
-----------------------------------------------------------

for _, edge in ipairs({
    -- Ships
    { from = "DOCK_STORMWIND", to = "DOCK_AUBERDINE_STORMWIND", method = "ship", cost = 170, loadingScreens = 1, requirements = { faction = "Alliance" } }, -- new in Forever; T = 55, D = 60 -> 2T + D = 170, crosses continents so one loading screen

    -- Auberdine -> Menethil -> Southshore -> Auberdine: one-directional LOOP,
    -- all live-measured, D = 60 at every stop. This replaced the old direct
    -- Auberdine <-> Menethil boat; the Atlas site still lists that route but it
    -- was confirmed absent live, so there is deliberately no direct edge.
    --   Auberdine -> Menethil   T = 65,  loading screen
    --   Menethil -> Southshore  T = 135, no loading screen (same continent)
    --   Southshore -> Auberdine T = 75,  loading screen
    -- Cycle C = 3*60 + 65 + 135 + 75 = 455. Average cost for a boat that
    -- visits X then Y = C/2 + ride time from X to Y (ride includes the 60s
    -- dock at any stop you stay aboard through). One edge per ordered pair so
    -- staying aboard doesn't get charged a second wait.
    { from = "DOCK_AUBERDINE_MENETHIL", to = "DOCK_MENETHIL", method = "ship", cost = 293, loadingScreens = 1, oneway = true, requirements = { faction = "Alliance" } }, -- ride 65
    { from = "DOCK_MENETHIL", to = "DOCK_SOUTHSHORE", method = "ship", cost = 363, loadingScreens = 0, oneway = true, requirements = { faction = "Alliance" } }, -- ride 135
    { from = "DOCK_SOUTHSHORE", to = "DOCK_AUBERDINE_MENETHIL", method = "ship", cost = 303, loadingScreens = 1, oneway = true, requirements = { faction = "Alliance" } }, -- ride 75
    { from = "DOCK_AUBERDINE_MENETHIL", to = "DOCK_SOUTHSHORE", method = "ship", cost = 488, loadingScreens = 1, oneway = true, requirements = { faction = "Alliance" } }, -- via Menethil, ride 65 + 60 + 135
    { from = "DOCK_MENETHIL", to = "DOCK_AUBERDINE_MENETHIL", method = "ship", cost = 498, loadingScreens = 1, oneway = true, requirements = { faction = "Alliance" } }, -- via Southshore, ride 135 + 60 + 75
    { from = "DOCK_SOUTHSHORE", to = "DOCK_MENETHIL", method = "ship", cost = 428, loadingScreens = 2, oneway = true, requirements = { faction = "Alliance" } }, -- via Auberdine, ride 75 + 60 + 65

    { from = "DOCK_STEAMWHEEDLE", to = "DOCK_POWDERFUSE", method = "ship", cost = 90, loadingScreens = 1 }, -- new in Forever, both factions; Kalimdor <-> Eastern Kingdoms (Riverglades) so it should have a loading screen (cost still a PLACEHOLDER)
    -- Menethil <-> Theramore shuttle: T = 155, D = 60 -> average 2T + D = 370. Crosses continents (one loading screen).
    { from = "DOCK_MENETHIL_THERAMORE", to = "DOCK_THERAMORE", method = "ship", cost = 370, loadingScreens = 1, requirements = { faction = "Alliance" } }, -- Classic
    { from = "DOCK_AUBERDINE_RUTTHERAN", to = "DOCK_RUTTHERAN", method = "ship", cost = 190, loadingScreens = 0, requirements = { faction = "Alliance" } }, -- Classic, Teldrassil ferry; T = 65, D = 60 -> 2T + D = 190, same continent so no loading screen
    { from = "DOCK_BOOTYBAY", to = "DOCK_RATCHET", method = "ship", cost = 90, loadingScreens = 1 }, -- Classic, both factions, Steamwheedle Cartel; Eastern Kingdoms <-> Kalimdor so it has a loading screen (cost still a PLACEHOLDER)
    { from = "DOCK_FEATHERMOON", to = "DOCK_FORGOTTENCOAST", method = "ship", cost = 60, loadingScreens = 0, requirements = { faction = "Alliance" } }, -- Classic ferry to Sardor Isle; same continent, no loading screen (cost still a PLACEHOLDER)

    -- Skyborne starting-island ships. Shuttle-boat cost model (T = transit,
    -- D = dock time): best case T (boarding as it leaves), worst case 3T + 2D
    -- (just missed it: away trip + dock + return trip + dock + your ride), so
    -- the average is 2T + D. Excludes loading tax.
    -- Horde: T = 140, D = 30 -> best 140, worst 480, average 310.
    -- All dock positions captured live via `/mzdump here`.
    { from = "DOCK_VALANAAR", to = "DOCK_SKYWATCHER", method = "ship", cost = 310, requirements = { faction = "Horde" } }, -- Zephras Isle <-> Mulgore, new in Forever
    -- Alliance: T = 115, D = 60 -> best 115, worst 465, average 290.
    { from = "DOCK_ZEPHRAS_ALLIANCE", to = "DOCK_DALARAN", method = "ship", cost = 290, requirements = { faction = "Alliance" } }, -- Zephras Isle <-> Dalaran (Alterac Mountains), new in Forever

    -- Dalaran <-> Stormwind "Skyborne Portal" (bidirectional, portals at both ends).
    -- Confirmed live: restricted to the Skyborne race, and it does NOT go away
    -- after the "Welcome to Azeroth" intro quest (94947), so no quest requirement.
    -- Race value is the confirmed UnitRace raceFile token ("Skyborne", raceID 95;
    -- the display name is "High Order Skyborne"). One loading screen (confirmed live).
    -- Cost is just the base portal cost; loading tax is added separately.
    { from = "PORTAL_DALARAN_STORMWIND", to = "PORTAL_STORMWIND_DALARAN", method = "portal", cost = 2, loadingScreens = 1, requirements = { faction = "Alliance", race = "Skyborne" } },

    -- The Wizard's Sanctum's door: its own nested container has no walking edges to the rest of
    -- Stormwind's (see Nodes_EasternKingdoms.lua), so this authored zero-cost step is the only way
    -- across, the way a walled city's own gate is. Reverse is generated automatically.
    { from = "ENTRANCE_SW_WIZARDS_SANCTUM_OUTER", to = "ENTRANCE_SW_WIZARDS_SANCTUM_INNER", method = "walk", cost = 0 },

    -- Rut'theran <-> Darnassus: bidirectional, both ends captured live. Not a
    -- real portal (nothing to interact with) -- just walking into a zone
    -- trigger, so it's method "transition", no faction requirement, and one
    -- loading screen.
    { from = "PORTAL_RUTTHERAN_DARNASSUS", to = "PORTAL_DARNASSUS_RUTTHERAN", method = "transition", cost = 2, loadingScreens = 1 }, -- Rut'theran <-> Darnassus

    -- Zeppelins (Horde only)
    -- Same shuttle model as the ships (average = 2T + D). Orgrimmar<->Grom'gol
    -- measured live: T = 60, D = 60 -> best 60, worst 300, average 180.
    { from = "ZEPPELIN_ORGRIMMAR", to = "ZEPPELIN_TIRISFAL", method = "zeppelin", cost = 180, requirements = { faction = "Horde" } }, -- estimated from the Orgrimmar<->Grom'gol measurement, not independently timed
    { from = "ZEPPELIN_ORGRIMMAR", to = "ZEPPELIN_GROMGOL", method = "zeppelin", cost = 180, requirements = { faction = "Horde" } }, -- MEASURED live: T = 60, D = 60
    { from = "ZEPPELIN_TIRISFAL", to = "ZEPPELIN_GROMGOL", method = "zeppelin", cost = 180, requirements = { faction = "Horde" } }, -- estimated from the Orgrimmar<->Grom'gol measurement, not independently timed

    -- Deeprun Tram (Alliance only), exterior entrance to exterior entrance.
    -- Cost is everything inside the instance (run to platform + wait + ride +
    -- run out), excluding loading tax: 120s average, timed live. Two loading
    -- screens (in, out) are added by the engine via loadingScreens.
    -- The interior has no usable map position, so it has no nodes of its own.
    { from = "TRAM_STORMWIND", to = "TRAM_IRONFORGE", method = "tram", cost = 120, loadingScreens = 2, requirements = { faction = "Alliance" } }, -- Stormwind <-> Ironforge
}) do
    table.insert(addon.Edges, edge)
end
