-- InstanceNames_enUS.lua (Forever) -- GENERATED by tools/gen_pois.py.
--
-- English names for instance entrances whose area id hasn't been checked in game yet.
-- Give the instance an area id in tools/poi_source/instances.tsv to have the client
-- name it instead (and this string goes away).

local addonName, addon = ...
if addon.RULESET ~= "forever" then return end   -- one addon for both games: this data is Forever's (Constants.lua)

addon:RegisterLocale("enUS", {
    NODE_INSTANCE_CITY_OF_DALARAN = "City of Dalaran",
    NODE_INSTANCE_EXCAVATION_SITE_WETLANDS = "Excavation Site: Wetlands",
    NODE_INSTANCE_RUINS_OF_LORDAERON = "Ruins of Lordaeron",
    NODE_INSTANCE_THE_HALL_OF_THANES = "The Hall of Thanes",
})
