-- TownNames_enUS.lua (Forever) -- GENERATED by tools/gen_pois.py.
--
-- English names for cities and towns that have no flight master to take a name from.
-- Move one out of here by giving it an `area` id whose client name matches.

local addonName, addon = ...
if addon.RULESET ~= "forever" then return end   -- one addon for both games: this data is Forever's (Constants.lua)

addon:RegisterLocale("enUS", {
    TOWN_BLOODHOOF_VILLAGE = "Bloodhoof Village",
    TOWN_BRILL = "Brill",
    CITY_DARNASSUS = "Darnassus",
    TOWN_DOLANAAR = "Dolanaar",
    TOWN_KHARANOS = "Kharanos",
    TOWN_LAKESHIRE = "Lakeshire",
    TOWN_LIGHTS_HOPE_CHAPEL = "Light's Hope Chapel",
    TOWN_RAZOR_HILL = "Razor Hill",
})
