-- Containers.lua (Modern) -- GENERATED by tools/gen_modern_nodes.py.
-- fly = false is mined from the old Constants.lua's NO_FLY_MAPS table, matched against
-- the containers the node conversion actually produced (see CONVERSION_NOTES.md for
-- 1 NO_FLY_MAPS mapID(s) with no node on them in this data to match against).
-- indoor = true is set for every interior container this pass made (see its own note
-- in CONVERSION_NOTES.md about per-mapID, not per-room, grouping).

local addonName, addon = ...

addon.Containers = addon.Containers or {}
addon.Containers[""] = { fly = true, indoor = false }   -- Modern has flying broadly, unlike Forever

addon.Containers["argus_antoran_wastes.map885"] = { fly = false } -- Antoran Wastes
addon.Containers["argus_eredath.map882"] = { fly = false } -- Eredath
addon.Containers["argus_krokuun.map830"] = { fly = false } -- Krokuun
addon.Containers["argus_vindicaar.map883"] = { fly = false } -- Vindicaar, Argus
addon.Containers["darkmoon_faire.map407"] = { fly = false } -- Darkmoon Island
addon.Containers["draenei_home.map103"] = { fly = false } -- Exodar
addon.Containers["draenei_home.map106"] = { fly = false } -- Bloodmyst Isle
addon.Containers["draenei_home.map97"] = { fly = false } -- Azuremyst Isle
addon.Containers["ek_overworld.map2509"] = { fly = false } -- Coiled Isle / Vaults of Atal'Utek (12.1) -- mount-only, no flying
addon.Containers["queldanas.map122"] = { fly = false } -- Isle of Quel'Danas
addon.Containers["quelthalas.map110"] = { fly = false } -- Silvermoon City
addon.Containers["quelthalas.map95"] = { fly = false } -- Ghostlands
addon.Containers["sl_oribos.map1670"] = { fly = false } -- Oribos
addon.Containers["sl_oribos.map1671"] = { fly = false } -- Oribos (Ring)
addon.Containers["sl_the_maw.map1543"] = { fly = false } -- The Maw
addon.Containers["timeless_isle.map554"] = { fly = false } -- Timeless Isle
addon.Containers["undermine.map2346"] = { fly = false } -- Undermine (11.1)

addon.Containers["broken_isles.map715.interior"] = { indoor = true } -- 9 interior node(s)
addon.Containers["broken_isles.map734.interior"] = { indoor = true } -- 1 interior node(s)
addon.Containers["ek_overworld.map35.interior"] = { indoor = true } -- 2 interior node(s)
addon.Containers["ek_overworld.map84.interior"] = { indoor = true } -- 17 interior node(s)
addon.Containers["kalimdor_overworld.map85.interior"] = { indoor = true } -- 17 interior node(s)
