-- Containers.lua (Modern) -- GENERATED by tools/gen_modern_nodes.py.
-- fly = false is mined from the old Constants.lua's NO_FLY_MAPS table, matched against
-- the containers the node conversion actually produced (see CONVERSION_NOTES.md for
-- 0 NO_FLY_MAPS mapID(s) with no node on them in this data to match against).
-- indoor = true is set for every interior container this pass made (see its own note
-- in CONVERSION_NOTES.md about per-mapID, not per-room, grouping).

local addonName, addon = ...
if addon.RULESET ~= "modern" then return end   -- one addon for both games: this data is Modern's (Constants.lua)

addon.Containers = addon.Containers or {}
addon.Containers[""] = { fly = true, indoor = false }   -- Modern has flying broadly, unlike Forever

addon.Containers["argus_antoran_wastes.map885"] = { fly = false } -- Antoran Wastes
addon.Containers["argus_eredath.map882"] = { fly = false } -- Eredath
addon.Containers["argus_krokuun.map830"] = { fly = false } -- Krokuun
addon.Containers["argus_vindicaar.map883"] = { fly = false } -- Vindicaar, Argus
addon.Containers["darkmoon_faire.map407"] = { fly = false } -- Darkmoon Island
addon.Containers["draenei_home.map103"] = { fly = false } -- Exodar
addon.Containers["draenei_home.map106"] = { fly = false } -- Bloodmyst Isle
addon.Containers["draenei_home.map97"] = { fly = false } -- Azuremyst Isle
addon.Containers["ek_overworld.map2509"] = { fly = false } -- Coiled Isle / Vaults of Atal'Utek (12.1) -- mount-only, no flying
addon.Containers["queldanas.map122"] = { fly = false } -- Isle of Quel'Danas
addon.Containers["quelthalas.map110"] = { fly = false } -- Silvermoon City
addon.Containers["quelthalas.map94"] = { fly = false } -- Eversong Woods
addon.Containers["quelthalas.map95"] = { fly = false } -- Ghostlands
addon.Containers["sl_oribos.map1670"] = { fly = false } -- Oribos
addon.Containers["sl_oribos.map1671"] = { fly = false } -- Oribos (Ring)
addon.Containers["sl_the_maw.map1543"] = { fly = false } -- The Maw
addon.Containers["timeless_isle.map554"] = { fly = false } -- Timeless Isle
addon.Containers["undermine.map2346"] = { fly = false } -- Undermine (11.1)

addon.Containers["broken_isles.map715.interior"] = { indoor = true } -- 9 interior node(s)
addon.Containers["broken_isles.map734.interior"] = { indoor = true } -- 1 interior node(s)
addon.Containers["ek_overworld.map35.interior"] = { indoor = true } -- 2 interior node(s)
addon.Containers["ek_overworld.map84.interior"] = { indoor = true } -- 17 interior node(s)
addon.Containers["kalimdor_overworld.map85.interior"] = { indoor = true } -- 17 interior node(s)
addon.Containers["ek_overworld.map2649"] = { indoor = true } -- hand-marked interior (tools/modern_manual.py)
addon.Containers["deeprun_tram"] = { indoor = true } -- hand-marked interior (tools/modern_manual.py)
addon.Containers["ek_overworld.map2393.interior"] = { indoor = true } -- hand-marked interior (tools/modern_manual.py)
addon.Containers["brawlgar_arena"] = { indoor = true } -- hand-marked interior (tools/modern_manual.py)

-- Phase groups (Zidormi's zones): phaseSide is the side's map art id, phaseMap the map whose art shows it.
addon.Containers["ek_overworld.map17_art18"] = { phaseGroup = "blasted_lands", phaseSide = 18, phaseMap = 17 }
addon.Containers["ek_overworld.map17_art628"] = { phaseGroup = "blasted_lands", phaseSide = 628, phaseMap = 17 }
addon.Containers["ek_overworld.map18_art19"] = { phaseGroup = "tirisfal", phaseSide = 19, phaseMap = 18 }
addon.Containers["ek_overworld.map2070_art1136"] = { phaseGroup = "tirisfal", phaseSide = 1136, phaseMap = 2070 }
addon.Containers["kalimdor_overworld.map1527_art260"] = { phaseGroup = "uldum", phaseSide = 260, phaseMap = 1527 }
addon.Containers["kalimdor_overworld.map249_art289"] = { phaseGroup = "uldum", phaseSide = 289, phaseMap = 249 }
addon.Containers["kalimdor_overworld.map62_art1176"] = { phaseGroup = "darkshore", phaseSide = 1176, phaseMap = 62 }
addon.Containers["kalimdor_overworld.map62_art67"] = { phaseGroup = "darkshore", phaseSide = 67, phaseMap = 62 }
addon.Containers["kalimdor_overworld.map70_art498"] = { phaseGroup = "dustwallow", phaseSide = 498, phaseMap = 70 }
addon.Containers["kalimdor_overworld.map70_art75"] = { phaseGroup = "dustwallow", phaseSide = 75, phaseMap = 70 }
addon.Containers["kalimdor_overworld.map81_art86"] = { phaseGroup = "silithus", phaseSide = 86, phaseMap = 81 }
addon.Containers["kalimdor_overworld.map81_art962"] = { phaseGroup = "silithus", phaseSide = 962, phaseMap = 81 }
addon.Containers["pandaria.map1530_art1342"] = { phaseGroup = "vale", phaseSide = 1342, phaseMap = 1530 }
addon.Containers["pandaria.map390_art402"] = { phaseGroup = "vale", phaseSide = 402, phaseMap = 390 }
addon.Containers["teldrassil.map57_art67"] = { phaseGroup = "darkshore", phaseSide = 67, phaseMap = 62 }
addon.Containers["teldrassil.map89_art67"] = { phaseGroup = "darkshore", phaseSide = 67, phaseMap = 62 }
