-- HolidayRoutes.lua (Modern) -- GENERATED by tools/gen_holiday_routes.py from tools/holiday_source/, do not hand-edit.
-- The routes the picker offers while their holiday is on (MultiRoute:HolidayRoutes): each has its stops for everyone
-- (neutral) and for each faction, as /way lines naming their maps.

local addonName, addon = ...
if addon.RULESET ~= "modern" then return end   -- one addon for both games: this data is Modern's (Constants.lua)

addon.HolidayRoutes = {
    { name = "Tricks and Treats of Eastern Kingdoms", holiday = "hallows_end",
      neutral = [[
/way #23 75.6 52.3 Light's Hope Chapel
/way #32 39.5 66.1 Iron Summit
/way #15 65.8 35.6 Fuselight
/way #51 71.6 14.1 Bogpaddle
/way #210 40.9 73.7 Booty Bay
/way #201 63.5 60.2 Deepmist Grotto
/way #205 49.2 41.8 Silver Tide Hollow
]],
      alliance = [[
/way #22 43.4 84.4 Chillwind Camp
/way #26 14.2 44.7 Aerie Peak
/way #26 66.2 44.4 Stormfeather Outpost
/way #56 26.1 26 Swiftgear Station
/way #56 10.8 61 Menethil Harbor
/way #56 58.2 39.2 Greenwarden's Grove
/way #48 35.5 48.5 Thelsamar
/way #48 83 63.5 Farstrider Lodge
/way #27 54.5 50.8 Kharanos
/way #87 18.5 50.9 The Commons
/way #15 20.9 56.3 Dragon's Mouth
/way #84 60.5 75.2 Trade District
/way #37 43.8 66 Goldshire
/way #49 26.5 41.5 Lakeshire
/way #51 28.9 32.4 The Harborage
/way #17 60.7 14.1 Nethergarde Keep
/way #17 44.4 87.6 Surwich
/way #47 73.8 44.2 Darkshire
/way #52 52.9 53.7 Sentinel Hill
/way #50 53.2 67 Fort Livingston
/way #14 40.1 49 Refuge Point
/way #241 49.6 30.4 Thundermar
/way #241 60.3 58.2 Firebeard's Patrol
/way #241 79.5 78.5 Highbank
/way #241 43.5 57.3 Victor's Point
/way #205 49.7 57.4 Tranquil Wash
/way #204 54.7 72.1 Darkbreak Cove
]],
      horde = [[
/way #110 79.4 57.7 Silvermoon City Inn
/way #110 67.6 72.9 Wayfarer's Rest
/way #94 48.2 47.9 Falconwing Square
/way #94 43.7 71 Fairbreeze Village
/way #95 48.7 31.9 Tranquillien
/way #22 48.3 63.7 Andorhal
/way #18 83 72.1 The Bulwark
/way #18 61 51.4 Brill
/way #90 67.7 37.5 Trade Quarter
/way #21 44.3 20.3 Forsaken Rear Guard
/way #21 46.4 42.7 The Sepulcher
/way #25 57.9 47.3 Tarren Mill
/way #25 60.3 63.7 Eastpoint Tower
/way #26 31.8 57.9 Hiri'watha Research Station
/way #26 78.2 81.5 Revantusk Village
/way #14 69 33.3 Hammerfall
/way #15 18.4 42.7 New Kargath
/way #51 46.9 56.9 Stonard
/way #17 40.5 11.3 Dreadmaul Hold
/way #50 37.4 51.8 Grom'gol Base Camp
/way #210 35 27.2 Hardwrench Hideaway
/way #241 45.1 76.8 Crushblow
/way #241 53.4 42.8 Bloodgulch
/way #241 75.4 16.5 The Krazzworks
/way #241 75.3 54.9 Dragonmaw Port
/way #205 51.4 62.3 Legion's Rest
/way #204 51.3 60.5 Tenebrous Cavern
]],
    },
    { name = "Tricks and Treats of Kalimdor", holiday = "hallows_end",
      neutral = [[
/way #70 41.9 74.1 Mudsprocket
/way #66 56.7 50.1 Karnum's Glade
/way #77 44.7 29 Whisperwind Grove
/way #83 59.8 51.1 Everlook
/way #71 55.7 61 Bootlegger Outpost
/way #71 52.6 27.1 Gadgetzan
/way #78 55.3 62.1 Marshal's Stand
/way #81 55.5 36.8 Cenarion Hold
/way #10 67.3 74.6 Ratchet
/way #198 63.1 24.1 Nordrassil Inn
/way #198 42.7 45.7 Shrine of Aviana
/way #198 18.6 37.3 Grove of Aessina
/way #1527 26.6 7.2 Oasis of Vir'sar
/way #1527 54.7 33 Ramkahen
]],
      alliance = [[
/way #199 39 11 Honor's Stand
/way #199 65.6 46.5 Northwatch Hold
/way #199 49 68.5 Fort Triumph
/way #70 66.6 45.3 Theramore Isle
/way #69 46.3 45.2 Feathermoon Stronghold
/way #69 51.1 17.8 Dreamer's Rest
/way #66 66.3 6.6 Nijel's Point
/way #65 40.6 17.7 Stonetalon Peak
/way #65 71 79 Northwatch Expedition Base Camp
/way #65 59 56.3 Windshear Hold
/way #65 31.5 60.7 Farwatcher's Glen
/way #65 39.5 32.8 Thal'darah Overlook
/way #63 37 49.3 Astranaar
/way #77 61.9 26.7 Talonbranch Glade
/way #62 50.8 18.8 Lor'danel
/way #89 62.2 33.1 Craftsmen's Terrace
/way #57 55.4 52.3 Dolanaar
/way #106 55.7 60 Blood Watch
/way #97 48.5 49 Azure Watch
/way #97 59.3 18.5 The Exodar
]],
      horde = [[
/way #63 12.9 34.1 Zoram'gar Outpost
/way #63 38.6 42.4 Hellscream's Watch
/way #63 50.2 67.3 Silverwind Refuge
/way #63 73.9 60.6 Splintertree Post
/way #76 57 50.3 Bilgewater Harbor
/way #70 36.8 32.4 Brackenwall Village
/way #66 24.1 68.3 Shadowprey Village
/way #69 74.8 45.1 Camp Mojache
/way #69 52 47.6 Stonemaul Hold
/way #69 41.4 15.7 Camp Ataya
/way #199 40.7 69.3 Desolation Hold
/way #199 39.3 20.1 Hunter's Hill
/way #7 46.8 60.4 Bloodhoof Village
/way #88 45.6 64.9 Thunder Bluff
/way #65 50.4 63.8 Sun Rock Retreat
/way #65 66.5 64.2 Krom'gar Fortress
/way #10 62.5 16.6 Nozzlepot's Outpost
/way #10 56.2 40 Grol'dom Farm
/way #10 49.5 57.9 Crossroads
/way #1 51.6 41.6 Razor Hill
/way #85 53.6 78.7 Valley of Strength
]],
    },
    { name = "Tricks and Treats of Outland", holiday = "hallows_end",
      neutral = [[
/way #109 43.4 36.1 Stormspire
/way #109 32.1 64.5 Area 52
/way #102 78.5 62.9 Cenarion Refuge
/way #111 28.1 49 Aldor Rise
/way #111 56.2 81.8 Scryers Tier
/way #104 61 28.2 Altar of Sha’tar
/way #104 56.3 59.8 Sanctum of the Stars
/way #105 62.9 38.3 Evergrove
]],
      alliance = [[
/way #105 61.1 68.1 Toshley's Station
/way #105 35.8 63.7 Sylvanaar
/way #102 41.9 26.2 Orebor Harborage
/way #102 67.2 48.9 Telredor
/way #100 23.4 36.4 Temple of Telhamat
/way #100 54.2 63.7 Honor Hold
/way #104 37 58.3 Wildhammer Stronghold
/way #108 56.6 53.2 Allerian Stronghold
/way #107 54.2 75.9 Telaar
]],
      horde = [[
/way #105 76.2 60.4 Mok'Nathal Village
/way #105 53.4 55.5 Thunderlord Stronghold
/way #102 30.7 50.9 Zabra'jin
/way #100 56.8 37.5 Thrallmar
/way #100 26.9 59.6 Falcon Watch
/way #107 56.7 34.6 Garadar
/way #108 48.8 45.2 Stonebreaker Hold
/way #104 30.3 27.8 Shadowmoon Village
]],
    },
    { name = "Tricks and Treats of Northrend", holiday = "hallows_end",
      neutral = [[
/way #121 40.8 66 The Argent Stand
/way #121 59.3 57.1 Zim'Torga
/way #119 26.6 59.2 Nesingwary Base Camp
/way #120 41 85.8 K3
/way #120 30.9 37.1 Bouldercrag's Refuge
/way #117 25.4 59.8 Kamagua
/way #115 60.1 53.4 Wyrmrest Temple
/way #115 48.1 74.6 Moa'ki Harbor
/way #126 37.8 46.4 The Underbelly
/way #125 48.3 40.8 The Legerdemain Lounge
/way #114 78.4 49.1 Unu'pe
]],
      alliance = [[
/way #114 57.1 18.8 Fizzcrank Airstrip
/way #114 58.5 67.8 Valiance Keep
/way #125 42.3 63 Silver Enclave
/way #115 28.9 56.2 Stars' Rest
/way #115 77.5 51.2 Wintergarde Keep
/way #116 31.9 60.2 Amberpine Lodge
/way #116 59.6 26.3 Westfall Brigade
/way #117 60.4 15.9 Fort Wildervar
/way #117 58.3 62.8 Valgarde
/way #117 30.8 41.4 Westguard Keep
/way #120 28.7 74.2 Frosthold
]],
      horde = [[
/way #120 37 49.5 Grom'arsh Crash Site
/way #120 67.6 50.6 Camp Tunka'lo
/way #117 79.2 30.6 Vengeance Landing
/way #117 52.1 66.1 New Agamand
/way #117 49.4 10.7 Camp Winterhoof
/way #116 20.8 64.7 Conquest Hold
/way #116 65.3 47 Camp Onegwah
/way #115 76.8 63.2 Venomspite
/way #115 37.8 46.4 Agmar's Hammer
/way #125 66.8 29.6 Sunreaver's Sanctuary
/way #114 41.7 54.4 Warsong Hold
/way #114 49.7 9.9 Bor'gorok Outpost
/way #114 76.6 37.4 Taunka'le Village
]],
    },
    { name = "Tricks and Treats of Pandaria", holiday = "hallows_end",
      neutral = [[
/way #422 55.9 32.2 Klaxxi'vess
/way #422 55.2 71.2 Soggy's Gamble
/way #371 45.7 43.6 Dawn's Blossom
/way #371 48 34.6 Greenstone Village
/way #371 54.6 63.3 Jade Temple Grounds
/way #371 55.7 24.4 Sri-La Village
/way #371 41.6 23.1 Tian Monastery
/way #418 51.4 77.2 Marista
/way #418 75.9 6.87 Zhu's Watch
/way #379 72.7 92.2 Binan Village
/way #379 64.2 61.2 The Grummle Bazaar
/way #379 57.4 59.9 One Keg
/way #379 62.3 29 Zouchin Village
/way #433 55 72.2 Tavern in the Mists
/way #388 71.1 57.8 Longying Outpost
/way #390 35.1 77.7 Mistfall Village
/way #376 83.6 20.1 Pang's Stead
/way #376 19.8 55.7 Stoneplow
]],
      alliance = [[
/way #371 44.8 84.4 Paw'don Village
/way #371 59.6 83.2 Pearlfin Village
/way #379 54.1 82.8 Westwind Rest
/way #390 87 69 Shrine of Seven Stars
]],
      horde = [[
/way #371 28 47.4 Grookin Hill
/way #371 28.4 13.2 Honeydew Village
/way #418 28.2 50.7 Dawnchaser Retreat
/way #418 61 25.1 Thunder Cleft
/way #379 62.7 80.5 Eastwind Rest
/way #390 61.9 16.2 Shrine of Two Moons
]],
    },
    { name = "Tricks and Treats of the Dragon Isles", holiday = "hallows_end",
      neutral = [[
/way #2023 46.2 40.6 Broadhoof Outpost
/way #2023 66.3 24.5 Emberwatch
/way #2023 72.1 80.4 Forkriver Crossing
/way #2023 62.9 40.6 Maruukai
/way #2023 57.1 76.7 Ohn'iri Springs
/way #2023 81.3 59.2 Pinewood Post
/way #2023 85.9 35.4 Rusza'thar Reach
/way #2023 28.6 60.6 Shady Sanctuary
/way #2023 41.9 60.4 Teerakai
/way #2023 85 26 Timberstep Outpost
/way #2025 50.1 42.7 Algeth'era Court
/way #2025 35.1 79.2 Garden Shrine
/way #2025 52.4 69.8 Gelikyr Post
/way #2025 59.9 82.7 Temporal Conflux
/way #2024 47 40.3 Camp Antonidas
/way #2024 62.8 57.7 Camp Nowhere
/way #2024 12.4 49.4 Iskaara
/way #2024 65.5 16.3 Theron's Watch
/way #2024 18.8 24.6 Three-Falls Lookout
/way #2151 33.9 58.8 Morqut Village
/way #2022 24.5 82.1 Apex Observatory
/way #2022 47.7 83.3 Dragonscale Basecamp
/way #2022 65.2 57.9 Life Vault Ruins
/way #2022 43.1 66.7 Obsidian Bulwark
/way #2022 25.8 55.2 Obsidian Throne
/way #2022 58 67.3 Ruby Lifeshrine
/way #2022 76.1 57.7 Skytop Observatory
/way #2022 53.9 39 Uktulut Backwater
/way #2022 46.4 27.4 Uktulut Pier
/way #2022 76.2 35.4 Wingrest Embassy
/way #2112 72.4 46.7 The Parting Glass
/way #2112 47.2 45.5 The Roasted Ram
/way #2112 22.4 30.9 Weyrnrest
/way #2133 56.4 56.4 Loamm
/way #2133 52.1 26.5 Obsidian Rest
]],
      alliance = [[
/way #2022 81.3 32 Wild Coast
]],
      horde = [[
/way #2022 80.4 27.9 Wild Coast
]],
    },
    { name = "Tricks and Treats of Khaz Algar", holiday = "hallows_end",
      neutral = [[
/way #2248 58.17 27.13 Rambleshire
/way #2248 42 74.39 Freywold Village
/way #2339 45.01 47.35 Dornogal
/way #2214 47.88 32.11 Gundargaz
/way #2214 61.85 46.26 Shadowvein Point
/way #2214 59.45 64.09 Camp Murroch
/way #2214 63.4 78.97 Opportunity Point
/way #2215 42.76 55.71 Mereldar
/way #2215 69.06 45.7 Dunelle's Kindness
/way #2215 49.13 39.54 Lorel's Crossing
/way #2215 40.58 67.98 Light's Redoubt
/way #2255 56.85 38.99 Weaver's Lair
/way #2255 58.96 18.62 Faerin's Advance
/way #2255 44.84 66.27 Wildcamp Ul'ar
/way #2255 77.96 62.8 Mmarl
/way #2216 49.75 22.27 Umbral Bazzar
/way #2216 62.08 41.38 High Hollows
/way #2216 57.42 38.47 The Burrows
]],
    },
}
