-- Nodes_IsolatedMaps.lua (Modern) -- GENERATED by tools/gen_modern_nodes.py from the original
-- addon's Mapzeroth_Data_Nodes_IsolatedMaps.lua, do not hand-edit. Geometry only (see the script's own
-- docstring for the conversion rules and known simplifications); names, factions,
-- edges and containers-flag overrides are separate, later passes.

local addonName, addon = ...

addon.Nodes = addon.Nodes or {}

addon.Nodes.IsolatedMaps = {
    { id = "VINDICAAR_AZEROTH", container = "vindicaar_azeroth.map940", mapID = 940, x = 0.7500, y = 0.7500 }, -- The Vindicaar (Azeroth)
    { id = "INSTANCE_SUNWELL_PLATEAU", container = "queldanas.map122", mapID = 122, x = 0.4800, y = 0.4200, kind = "instance", journal = 752 }, -- Sunwell Plateau
    { id = "QUELDANAS", container = "queldanas.map122", mapID = 122, x = 0.5000, y = 0.3660 }, -- Entrance Portal
    { id = "INSTANCE_MAGISTERS_TERRACE_BC", container = "queldanas.map122", mapID = 122, x = 0.6100, y = 0.3100, kind = "instance", journal = 249 }, -- Magisters' Terrace
    { id = "TAXI_213", container = "queldanas.map122", mapID = 122, x = 0.4740, y = 0.2510 }, -- Shattered Sun Staging Area
    { id = "TAXI_1294", container = "timeless_isle.map554", mapID = 554, x = 0.2250, y = 0.3810 }, -- Huojin Landing
    { id = "GRIM_CAMPFIRE_PANDARIA", container = "timeless_isle.map554", mapID = 554, x = 0.6790, y = 0.7690 }, -- Grim Campfire
    { id = "TIMELESS_ISLE", container = "timeless_isle.map554", mapID = 554, x = 0.3420, y = 0.5530 }, -- The Celestial Court
    { id = "TAXI_1293", container = "timeless_isle.map554", mapID = 554, x = 0.2300, y = 0.7100 }, -- Tushui Landing
    { id = "ARCANTINA_EXIT", container = "arcantina.map2541", mapID = 2541, x = 0.5067, y = 0.8530 }, -- Exit
    { id = "ARCANTINA_ENTRANCE", container = "arcantina.map2541", mapID = 2541, x = 0.5093, y = 0.7880 }, -- The Arcantina
    { id = "DARKMOON_ENTRANCE", container = "darkmoon_faire.map407", mapID = 407, x = 0.5129, y = 0.2386 }, -- Entrance
    { id = "DARKMOON_DOCK_EXIT", container = "darkmoon_faire.map407", mapID = 407, x = 0.5056, y = 0.9055 }, -- Dock
    { id = "PORTAL_HARANDAR_EVERSONG", container = "harandar.map2413", mapID = 2413, x = 0.7589, y = 0.5477 }, -- Rootway to Eversong
    { id = "PORTAL_HARANDAR_SILVERMOON", container = "harandar.map2576", mapID = 2576, x = 0.6413, y = 0.7066 }, -- Rootway to Silvermoon City
    { id = "TAXI_3192", container = "harandar.map2413", mapID = 2413, x = 0.6940, y = 0.5257 }, -- Har'athir Flightmaster
    { id = "TAXI_3195", container = "harandar.map2413", mapID = 2413, x = 0.3175, y = 0.6737 }, -- Har'alnor Flightmaster
    { id = "PORTAL_HARANDAR_VOIDSTORM", container = "harandar.map2405", mapID = 2405, x = 0.6186, y = 0.7318 }, -- Portal to Voidstorm
    { id = "TAXI_3196", container = "harandar.map2413", mapID = 2413, x = 0.3552, y = 0.2375 }, -- Har'mara Flightmaster
    { id = "INSTANCE_THE_DREAMRIFT", container = "harandar.map2413", mapID = 2413, x = 0.6102, y = 0.6266, kind = "instance", journal = 1314 }, -- The Dreamrift
    { id = "TAXI_3193", container = "harandar.map2576", mapID = 2576, x = 0.7090, y = 0.5321 }, -- The Den Flightmaster
    { id = "LOAKNIT_DEN_ZUL_AMAN", container = "harandar.map2413", mapID = 2413, x = 0.3160, y = 0.2120 }, -- Loaknit Den
    { id = "INSTANCE_THE_BLINDING_VALE", container = "harandar.map2413", mapID = 2413, x = 0.2659, y = 0.7804, kind = "instance", journal = 1309 }, -- The Blinding Vale
    { id = "TAXI_3194", container = "harandar.map2413", mapID = 2413, x = 0.6461, y = 0.2319 }, -- Har'kuai Flightmaster
    { id = "TAXI_3035", container = "karesh.map2472", mapID = 2472, x = 0.5415, y = 0.6277 }, -- Hosaas Rest
    { id = "KARESH", container = "karesh.map2472", mapID = 2472, x = 0.5970, y = 0.8400 }, -- Tazavesh Entrance Portal
    { id = "TAXI_3031", container = "karesh.map2472", mapID = 2472, x = 0.7655, y = 0.3481 }, -- The Oasis
    { id = "TAXI_3030", container = "karesh.map2472", mapID = 2472, x = 0.7022, y = 0.6083 }, -- Eco-Dome: Rhovan
    { id = "TAXI_3034", container = "karesh.map2472", mapID = 2472, x = 0.4773, y = 0.3709 }, -- Overlook Zo'Shuul
    { id = "INSTANCE_MANAFORGE_OMEGA", container = "karesh.map2472", mapID = 2472, x = 0.4100, y = 0.2100, kind = "instance", journal = 1302 }, -- Manaforge Omega
    { id = "TAXI_2703", container = "karesh.map2472", mapID = 2472, x = 0.6330, y = 0.6843 }, -- Tazavesh Flightmaster
    { id = "INSTANCE_ECO_DOME_ALDANI", container = "karesh.map2472", mapID = 2472, x = 0.4380, y = 0.0447, kind = "instance", journal = 1303 }, -- Eco-Dome Al'dani
    { id = "INSTANCE_TAZAVESH_THE_VEILED_MARKET", container = "karesh.map2472", mapID = 2472, x = 0.3619, y = 0.1245, kind = "instance", journal = 1194 }, -- Tazavesh, the Veiled Market
    { id = "TAXI_3033", container = "karesh.map2472", mapID = 2472, x = 0.4244, y = 0.2304 }, -- Shadow Point
    { id = "TAXI_3032", container = "karesh.map2472", mapID = 2472, x = 0.6055, y = 0.2911 }, -- Shan'dorah
    { id = "TAXI_1222", container = "isle_of_giants.map507", mapID = 507, x = 0.5157, y = 0.7504 }, -- Bozzle's Wreck
    { id = "TAXI_1221", container = "isle_of_giants.map507", mapID = 507, x = 0.4160, y = 0.7920 }, -- Beeble's Wreck
    { id = "PORTAL_VOIDSTORM_HARANDAR", container = "voidstorm.map2405", mapID = 2405, x = 0.5171, y = 0.7037 }, -- Portal to Harandar
    { id = "TAXI_3119", container = "voidstorm.map2405", mapID = 2405, x = 0.3688, y = 0.5895 }, -- The Ingress Flightmaster
    { id = "INSTANCE_VOIDSCAR_ARENA", container = "voidstorm.map2405", mapID = 2405, x = 0.5156, y = 0.1901, kind = "instance", journal = 1313 }, -- Voidscar Arena
    { id = "TAXI_3121", container = "voidstorm.map2405", mapID = 2405, x = 0.5118, y = 0.6921 }, -- Howling Ridge Flightmaster
    { id = "TAXI_3123", container = "voidstorm.map2405", mapID = 2405, x = 0.4459, y = 0.3945 }, -- Masters' Perch Flightmaster
    { id = "INSTANCE_NEXUS_POINT_XENAS", container = "voidstorm.map2405", mapID = 2405, x = 0.6477, y = 0.6163, kind = "instance", journal = 1316 }, -- Nexus Point Xenas
    { id = "PORTAL_VOIDSTORM_SILVERMOON", container = "voidstorm.map2405", mapID = 2405, x = 0.5164, y = 0.7020 }, -- Portal to Silvermoon
    { id = "PORTAL_VOIDSTORM_INGRESS", container = "voidstorm.map2405", mapID = 2405, x = 0.3415, y = 0.6060 }, -- Portal to Silvermoon
    { id = "INSTANCE_VOIDSPIRE", container = "voidstorm.map2405", mapID = 2405, x = 0.4520, y = 0.6494, kind = "instance", journal = 1307 }, -- Voidspire
    { id = "TAXI_3120", container = "voidstorm.map2405", mapID = 2405, x = 0.4223, y = 0.7368 }, -- Locus Point Flightmaster
    { id = "TAXI_2406", container = "nazjatar.map1355", mapID = 1355, x = 0.7360, y = 0.3990 }, -- Orise's Vigil
    { id = "FLIGHT_ASHEN_STRAND_HORDE", container = "nazjatar.map1355", mapID = 1355, x = 0.3426, y = 0.3690 }, -- Ashen Strand
    { id = "TAXI_2412", container = "nazjatar.map1355", mapID = 1355, x = 0.3568, y = 0.8263 }, -- Wreck of the Hungry Riverbeast
    { id = "TAXI_2404", container = "nazjatar.map1355", mapID = 1355, x = 0.4721, y = 0.6314 }, -- Newhome
    { id = "TAXI_2405", container = "nazjatar.map1355", mapID = 1355, x = 0.7912, y = 0.3806 }, -- Zin'Azshari
    { id = "FLIGHT_ASHEN_STRAND_ALLIANCE", container = "nazjatar.map1355", mapID = 1355, x = 0.3160, y = 0.3820 }, -- Ashen Strand
    { id = "TAXI_2437", container = "nazjatar.map1355", mapID = 1355, x = 0.6358, y = 0.5166 }, -- Ekka's Hideaway
    { id = "TAXI_2403", container = "nazjatar.map1355", mapID = 1355, x = 0.7397, y = 0.2466 }, -- Kelya's Grave
    { id = "TAXI_2409", container = "nazjatar.map1355", mapID = 1355, x = 0.4410, y = 0.8570 }, -- Wreck of the Old Blanchy
    { id = "NAZJATAR_ALLIANCE", container = "nazjatar.map1355", mapID = 1355, x = 0.3996, y = 0.5884 }, -- Mezzamere
    { id = "TAXI_2408", container = "nazjatar.map1355", mapID = 1355, x = 0.3990, y = 0.5420 }, -- Mezzamere
    { id = "INSTANCE_THE_ETERNAL_PALACE", container = "nazjatar.map1355", mapID = 1355, x = 0.5000, y = 0.1200, kind = "instance", journal = 1179 }, -- The Eternal Palace
    { id = "FLIGHT_THE_TIDAL_CONFLUX_ALLIANCE", container = "nazjatar.map1355", mapID = 1355, x = 0.4960, y = 0.2360 }, -- The Tidal Conflux
    { id = "FLIGHT_THE_TIDAL_CONFLUX_HORDE", container = "nazjatar.map1355", mapID = 1355, x = 0.5086, y = 0.2376 }, -- The Tidal Conflux
    { id = "TAXI_2407", container = "nazjatar.map1355", mapID = 1355, x = 0.6140, y = 0.3660 }, -- Utama's Stand
    { id = "NAZJATAR_HORDE", container = "nazjatar.map1355", mapID = 1355, x = 0.4719, y = 0.6263 }, -- Newhome
    { id = "SHADOWFORGE_CITY_MOLE", container = "dark_iron_city.map1186", mapID = 1186, x = 0.6140, y = 0.2440 }, -- Shadowforge City
    { id = "INSTANCE_SPOREFALL", container = "harandar.map2413", mapID = 2413, x = 0.7360, y = 0.6650, kind = "instance", journal = 1305 }, -- Sporefall (Harandar): a single-boss raid, entered from the open world (hand-added: tools/modern_manual.py)
}
