-- Nodes_BfA.lua (Modern) -- GENERATED by tools/gen_modern_nodes.py from the original
-- addon's Mapzeroth_Data_Nodes_BfA.lua, do not hand-edit. Geometry only (see the script's own
-- docstring for the conversion rules and known simplifications); names, factions,
-- edges and containers-flag overrides are separate, later passes.

local addonName, addon = ...

addon.Nodes = addon.Nodes or {}

addon.Nodes.BfA = {
    { id = "TAXI_625", container = "quelthalas.map94", mapID = 94, x = 0.4309, y = 0.6985 }, -- Fairbreeze Village
    { id = "TAXI_83", container = "quelthalas.map95", mapID = 95, x = 0.4592, y = 0.3054 }, -- Tranquillien
    { id = "TAXI_205", container = "quelthalas.map95", mapID = 95, x = 0.7350, y = 0.6710 }, -- Zul'Aman
    { id = "SILVERMOON", container = "quelthalas.map110", mapID = 110, x = 0.5826, y = 0.1924, city = "silvermoon_bc" }, -- Orgrimmar Portal
    { id = "TAXI_631", container = "quelthalas.map94", mapID = 94, x = 0.4629, y = 0.4665 }, -- Falconwing Square
    { id = "TAXI_82", container = "quelthalas.map110", mapID = 110, x = 0.6275, y = 0.9658, city = "silvermoon_bc" }, -- Flightmaster
    { id = "INSTANCE_ZULAMAN", container = "quelthalas.map95", mapID = 95, x = 0.8200, y = 0.6400, kind = "instance", journal = 77 }, -- Zul'Aman
    { id = "TAXI_2096", container = "tol_dagor.map974", mapID = 974, x = 0.3744, y = 0.9210 }, -- Tol Dagor Flightmaster
    { id = "INSTANCE_TOL_DAGOR", container = "tol_dagor.map974", mapID = 974, x = 0.3900, y = 0.7000, kind = "instance", journal = 1002 }, -- Tol Dagor
    { id = "TAXI_2276", container = "tol_dagor.map974", mapID = 974, x = 0.2296, y = 0.4654 }, -- Tol Dagor Flightmaster
    { id = "TAXI_2441", container = "mechagon.map1462", mapID = 1462, x = 0.7335, y = 0.2542 }, -- Prospectus Bay
    { id = "TAXI_2442", container = "mechagon.map1462", mapID = 1462, x = 0.7750, y = 0.4100 }, -- Overspark Expedition Camp
    { id = "MECHAGON", container = "mechagon.map1462", mapID = 1462, x = 0.7390, y = 0.3650, area = 10418 }, -- Rustbolt
    { id = "INSTANCE_OPERATION_MECHAGON", container = "mechagon.map1462", mapID = 1462, x = 0.7300, y = 0.3600, kind = "instance", journal = 1178 }, -- Operation: Mechagon
    { id = "TAXI_2035", container = "kul_tiras.map896", mapID = 896, x = 0.7000, y = 0.6010 }, -- Fletcher's Hollow
    { id = "TAXI_2091", container = "kul_tiras.map942", mapID = 942, x = 0.3874, y = 0.6692 }, -- Stonetusk Watch
    { id = "STORMSONG_VALLEY_MOLE", container = "kul_tiras.map942", mapID = 942, x = 0.6420, y = 0.2940, area = 9623 }, -- Tidebreak Summit
    { id = "TORTOLLAN_BASE_CAMP", container = "kul_tiras.map942", mapID = 942, x = 0.4030, y = 0.3650, area = 9693 }, -- Seekers Vista
    { id = "TAXI_2106", container = "kul_tiras.map896", mapID = 896, x = 0.3800, y = 0.5260 }, -- Arom's Stand
    { id = "BORALUS_PET", container = "kul_tiras.map1161", mapID = 1161, x = 0.5002, y = 0.4677, city = "boralus" }, -- Pet Shop
    { id = "TAXI_2275", container = "kul_tiras.map896", mapID = 896, x = 0.6181, y = 0.1695 }, -- Mudfisher Cove
    { id = "TAXI_2090", container = "kul_tiras.map942", mapID = 942, x = 0.5228, y = 0.7974 }, -- Hillcrest Pasture
    { id = "TAXI_2067", container = "kul_tiras.map895", mapID = 895, x = 0.7182, y = 0.5173 }, -- Timberfell Outpost
    { id = "TAXI_2278", container = "kul_tiras.map1161", mapID = 1161, x = 0.7630, y = 0.7280, city = "boralus" }, -- Mariner's Row
    { id = "TIRAGARDE_SOUND_MOLE", container = "kul_tiras.map895", mapID = 895, x = 0.8820, y = 0.7150 }, -- Wailing Tideways
    { id = "TAXI_2037", container = "kul_tiras.map896", mapID = 896, x = 0.6240, y = 0.2370 }, -- Barbthorn Ridge
    { id = "INSTANCE_WAYCREST_MANOR", container = "kul_tiras.map896", mapID = 896, x = 0.3400, y = 0.1300, kind = "instance", journal = 1021 }, -- Waycrest Manor
    { id = "TAXI_2062", container = "kul_tiras.map895", mapID = 895, x = 0.6169, y = 0.1341 }, -- Wolf's Den
    { id = "TAXI_2137", container = "kul_tiras.map942", mapID = 942, x = 0.3050, y = 0.6640 }, -- Millstone Hamlet
    { id = "TAXI_2108", container = "kul_tiras.map896", mapID = 896, x = 0.2710, y = 0.7210 }, -- Falconhurst
    { id = "TAXI_2034", container = "kul_tiras.map896", mapID = 896, x = 0.7080, y = 0.4030 }, -- Hangman's Point
    { id = "TAXI_2101", container = "kul_tiras.map942", mapID = 942, x = 0.5060, y = 0.7000 }, -- The Amber Waves
    { id = "INSTANCE_SIEGE_OF_BORALUS_HORDE", container = "kul_tiras.map895", mapID = 895, x = 0.8800, y = 0.5100, kind = "instance", journal = 1023, faction = "Horde" }, -- Siege of Boralus
    { id = "TAXI_2138", container = "kul_tiras.map942", mapID = 942, x = 0.3400, y = 0.4680 }, -- Fort Daelin
    { id = "INSTANCE_BATTLE_OF_DAZARALOR_ALLIANCE", container = "kul_tiras.map1161", mapID = 1161, x = 0.7000, y = 0.3500, city = "boralus", kind = "instance", journal = 1176, faction = "Alliance" }, -- Battle of Dazar'alor
    { id = "INSTANCE_SIEGE_OF_BORALUS_ALLIANCE", container = "kul_tiras.map895", mapID = 895, x = 0.7200, y = 0.2300, kind = "instance", journal = 1023, faction = "Alliance" }, -- Siege of Boralus
    { id = "INSTANCE_FREEHOLD", container = "kul_tiras.map895", mapID = 895, x = 0.8500, y = 0.7900, kind = "instance", journal = 1001 }, -- Freehold
    { id = "TAXI_2095", container = "kul_tiras.map942", mapID = 942, x = 0.7759, y = 0.2383 }, -- Shrine of the Storm
    { id = "BORALUS", container = "kul_tiras.map1161", mapID = 1161, x = 0.7060, y = 0.1700, city = "boralus" }, -- Portal Room
    { id = "TAXI_2086", container = "kul_tiras.map942", mapID = 942, x = 0.5940, y = 0.7020 }, -- Brennadam
    { id = "DOCK_BORALUS", container = "kul_tiras.map1161", mapID = 1161, x = 0.6805, y = 0.2651, city = "boralus" }, -- Dock
    { id = "TAXI_2109", container = "kul_tiras.map896", mapID = 896, x = 0.2565, y = 0.1640 }, -- Whitegrove Chapel
    { id = "TAXI_2077", container = "kul_tiras.map895", mapID = 895, x = 0.8626, y = 0.8106 }, -- Castaway Point
    { id = "TAXI_2092", container = "kul_tiras.map942", mapID = 942, x = 0.5404, y = 0.4891 }, -- Diretusk Hollow
    { id = "TAXI_2274", container = "kul_tiras.map896", mapID = 896, x = 0.6628, y = 0.5915 }, -- Swiftwind Post
    { id = "DOCK_PLUNDER_HARBOR", container = "kul_tiras.map895", mapID = 895, x = 0.8815, y = 0.5105 }, -- Plunder Harbor
    { id = "TAXI_2140", container = "kul_tiras.map895", mapID = 895, x = 0.8547, y = 0.5014 }, -- Plunder Harbor
    { id = "TAXI_2079", container = "kul_tiras.map895", mapID = 895, x = 0.7630, y = 0.6530 }, -- Kennings Lodge
    { id = "TAXI_2279", container = "kul_tiras.map895", mapID = 895, x = 0.5275, y = 0.6286 }, -- Stonefist Watch
    { id = "TAXI_2042", container = "kul_tiras.map895", mapID = 895, x = 0.5800, y = 0.6120 }, -- Vigil Hill
    { id = "TAXI_2088", container = "kul_tiras.map942", mapID = 942, x = 0.6850, y = 0.6500 }, -- Mildenhall Meadery
    { id = "TAXI_2023", container = "kul_tiras.map895", mapID = 895, x = 0.7723, y = 0.8263 }, -- Freehold
    { id = "TAXI_2087", container = "kul_tiras.map895", mapID = 895, x = 0.3530, y = 0.2470 }, -- Outrigger Post
    { id = "TAXI_2084", container = "kul_tiras.map895", mapID = 895, x = 0.5250, y = 0.2860 }, -- Norwington Estate
    { id = "DOCK_WARFANG_HOLD", container = "kul_tiras.map942", mapID = 942, x = 0.5193, y = 0.2434 }, -- Warfang Hold Dock
    { id = "TAXI_2083", container = "kul_tiras.map1161", mapID = 1161, x = 0.6670, y = 0.1510, city = "boralus" }, -- Tradewinds Market
    { id = "TAXI_2273", container = "kul_tiras.map895", mapID = 895, x = 0.3933, y = 0.1836 }, -- Waning Glacier
    { id = "TAXI_2133", container = "kul_tiras.map942", mapID = 942, x = 0.7790, y = 0.2910 }, -- Shrine of the Storm
    { id = "TAXI_2277", container = "kul_tiras.map1161", mapID = 1161, x = 0.4750, y = 0.6490, city = "boralus" }, -- Proudmoore Keep
    { id = "TAXI_2139", container = "kul_tiras.map942", mapID = 942, x = 0.6052, y = 0.2736 }, -- Windfall Cavern
    { id = "TAXI_2085", container = "kul_tiras.map942", mapID = 942, x = 0.6540, y = 0.4780 }, -- Tidecross
    { id = "TAXI_2127", container = "kul_tiras.map896", mapID = 896, x = 0.1900, y = 0.4326 }, -- Anyport
    { id = "TAXI_2094", container = "kul_tiras.map942", mapID = 942, x = 0.5098, y = 0.3372 }, -- Warfang Hold
    { id = "TAXI_2074", container = "kul_tiras.map895", mapID = 895, x = 0.7550, y = 0.4880 }, -- Bridgeport
    { id = "TAXI_2102", container = "kul_tiras.map895", mapID = 895, x = 0.4180, y = 0.2240 }, -- Roughneck Camp
    { id = "TAXI_2107", container = "kul_tiras.map896", mapID = 896, x = 0.3160, y = 0.3030 }, -- Watchman's Rise
    { id = "TAXI_2089", container = "kul_tiras.map942", mapID = 942, x = 0.3989, y = 0.3723 }, -- Seekers Vista
    { id = "TAXI_2097", container = "kul_tiras.map942", mapID = 942, x = 0.4260, y = 0.5710 }, -- Deadwash
    { id = "INSTANCE_SHRINE_OF_THE_STORM", container = "kul_tiras.map942", mapID = 942, x = 0.7800, y = 0.2400, kind = "instance", journal = 1036 }, -- Shrine of the Storm
    { id = "TAXI_2135", container = "kul_tiras.map896", mapID = 896, x = 0.3709, y = 0.2419 }, -- Krazzlefrazz Outpost
    { id = "TAXI_2060", container = "kul_tiras.map895", mapID = 895, x = 0.6650, y = 0.2310 }, -- Hatherford
    { id = "DOCK_ANYPORT", container = "kul_tiras.map896", mapID = 896, x = 0.2056, y = 0.4553 }, -- Anyport Dock
    { id = "INSTANCE_CRUCIBLE_OF_STORMS", container = "kul_tiras.map942", mapID = 942, x = 0.8400, y = 0.4700, kind = "instance", journal = 1177 }, -- Crucible of Storms
    { id = "TAXI_2033", container = "kul_tiras.map896", mapID = 896, x = 0.5490, y = 0.3480 }, -- Fallhaven
    { id = "TAXI_2093", container = "kul_tiras.map942", mapID = 942, x = 0.7570, y = 0.6392 }, -- Ironmaul Overlook
    { id = "BORDER_GHOSTLANDS_EVERSONG_BC", container = "quelthalas.map95", mapID = 95, x = 0.4843, y = 0.1068 }, -- Old Ghostlands: the road north into old Eversong (hand-added: tools/modern_manual.py)
    { id = "BORDER_EVERSONG_GHOSTLANDS_BC", container = "quelthalas.map94", mapID = 94, x = 0.4862, y = 0.9147 }, -- Old Eversong: the road south into the old Ghostlands (hand-added: tools/modern_manual.py)
    { id = "BORDER_EVERSONG_SILVERMOON_BC", container = "quelthalas.map94", mapID = 94, x = 0.5621, y = 0.4917 }, -- Old Eversong: outside old Silvermoon's gate (hand-added: tools/modern_manual.py)
    { id = "BORDER_SILVERMOON_EVERSONG_BC", container = "quelthalas.map110", mapID = 110, x = 0.7054, y = 0.8903, city = "silvermoon_bc" }, -- Old Silvermoon: inside its gate (hand-added: tools/modern_manual.py)
    { id = "PORTAL_GHOSTLANDS_EPL", container = "quelthalas.map95", mapID = 95, x = 0.5208, y = 0.9783 }, -- Old Ghostlands: the portal to the Eastern Plaguelands (Sanctum of the Sun) (hand-added: tools/modern_manual.py)
    { id = "PORTAL_BC_SILVERMOON_TIRISFAL", container = "quelthalas.map110", mapID = 110, x = 0.5068, y = 0.1643, city = "silvermoon_bc" }, -- Old Silvermoon: the portal to Tirisfal, and where the ways in from Tirisfal land (hand-added: tools/modern_manual.py)
}
