"""Writes tools/poi_source/npc_factions.tsv: which faction each trainer NPC will serve.

Wowhead's Forever NPC lists give every NPC's reaction to each faction (`react`: [Alliance,
Horde], 1 = friendly). An NPC friendly to one faction only is that faction's; friendly to
both, or to neither on record, it is left out (anyone). tools/gen_pois.py reads the file and
marks each trainer NPC, and falls back to its city or town's faction for an NPC not listed.

Two list pages (role filters 28 "Trainer" and 24 "Class trainer"), each under Wowhead's
1000-row cap; rerun when trainers are added.

    python tools/fetch_npc_factions.py
"""
import json
import pathlib
import time
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "tools" / "poi_source" / "npc_factions.tsv"
PAGES = ["https://www.wowhead.com/forever/npcs?filter=28;1;0", "https://www.wowhead.com/forever/npcs?filter=24;1;0"]


def listview(url):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    html = urllib.request.urlopen(req).read().decode("utf-8")
    i = html.find("new Listview")
    j = html.find("data: [", i)
    start = j + 6 if j > 0 else html.find('"data":', i) + 7
    depth = 0
    for k in range(start, len(html)):
        c = html[k]
        if c == "[":
            depth += 1
        elif c == "]":
            depth -= 1
            if depth == 0:
                rows = json.loads(html[start:k + 1])
                if len(rows) >= 1000:
                    raise SystemExit(f"{url}: 1000 rows, the list is capped; split it with another filter")
                return rows


def main():
    sides = {}
    for n, url in enumerate(PAGES):
        if n:
            time.sleep(2.5)
        for row in listview(url):
            alliance, horde = (row.get("react") or [None, None])[:2]
            if alliance == 1 and horde != 1:
                sides[row["id"]] = "Alliance"
            elif horde == 1 and alliance != 1:
                sides[row["id"]] = "Horde"
    lines = ["# npc id, faction (Alliance | Horde): the faction a trainer NPC serves, from Wowhead's reactions.",
             "# GENERATED by tools/fetch_npc_factions.py; NPCs friendly to both (or neither on record) aren't listed."]
    lines += [f"{npc}\t{side}" for npc, side in sorted(sides.items())]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(sides)} NPCs")


if __name__ == "__main__":
    main()
