"""tools/gen_modern_edges.py -- converts the original retail addon's edge list
(../Mapzeroth/Data/Mapzeroth_Data_Edges.lua) into the rebuild's edge schema
(Data/Modern/Edges.lua). Run after tools/gen_modern_nodes.py (this script checks every
edge's `from`/`to` against that pass's node ids and drops -- reporting -- any that don't
resolve). See docs/DESIGN.md section 4, and Data/Modern/CONVERSION_NOTES.md for the
node-conversion notes this appends to.

    python tools/gen_modern_edges.py

Cost: the old engine defaults an edge's omitted `cost` to a flat per-method constant
(Constants.lua's `TRAVEL_COSTS`); the new engine's omitted-cost fallback is distance-based
instead (right for `walk`, wrong for everything else -- see the node-conversion notes).
So every omitted-cost edge gets its method's old flat value written in literally, except
`walk`, which is left omitted on purpose: a Zone<->Zone walk should use real distance, the
same way Forever's own hand-authored walk edges do.

Requirements: `faction`/`class`/`minLevel`/`maxLevel`/`quest`/`holiday` carry over under
the same key (the new engine's EdgeRequirements.lua already has checkers for all of
these -- `holiday` needed adding, done alongside this pass, see Data/Modern/Game.lua/
PlayerAbilities.lua). `questNotCompleted` is renamed `notQuest` to match the new checker's
name; nothing else about it changes.

Phases (docs/DESIGN.md section 2): `mapArtID = { mapID, artID }` (the old phase gate) is not a
requirement in the new engine. It becomes the edge's `inPhase = { group, artID }`: the edge can
only be taken on that side of the group (Containers.lua's phase tags, written by
gen_modern_nodes.py, say which group an art id is a side of). A `phaseswitch` edge (talking to
Zidormi) gets `overridesPhase = { group }`: it moves the player to the side it lands on, both
ways (TravelGraph copies it onto the reverse).
"""
import pathlib
import re
import sys
from lupa.lua51 import LuaRuntime

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import modern_manual as manual
import modern_ids
import conversion_notes

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = pathlib.Path(r"C:\Users\shaun\Documents\Claude\Mapzeroth\Mapzeroth\Data\Mapzeroth_Data_Edges.lua")
OUT = ROOT / "Data" / "Modern"

# The old Constants.lua's TRAVEL_COSTS: what an omitted `cost` meant, by method. `walk` is
# excluded on purpose -- see the module docstring.
FALLBACK_COST = {
    "portal": 0, "teleport": 0, "hearthstone": 0, "racial": 0,
    "ship": 60, "zeppelin": 60, "tram": 90, "taxi": 120, "phaseswitch": 10,
}

# The old addon calls a taxi edge "flight"; the rebuild says "taxi", so it can't be mixed up with
# "fly" (a player flying their own mount between two points, generated by TravelGraph).
METHOD_RENAME = {"flight": "taxi"}
RENAME_REQUIREMENT = {"questNotCompleted": "notQuest"}
# Requirement keys turned into something else (mapArtID: inPhase, see the docstring); anything
# else unrecognized is a real gap this run should stop and report, not silently drop.
KNOWN_INERT_REQUIREMENTS = {"mapArtID"}
KNOWN_REQUIREMENTS = {"faction", "class", "race", "minLevel", "maxLevel", "quest", "notQuest",
                       "holiday", "anyOf", "anyQuest"}


# Same match files tools/gen_modern_nodes.py renames flight-master and instance-entrance
# node ids from -- an edge's from/to needs the identical rename or it'd point at an id that
# no longer exists.
MATCH_FILES = {
    "flight_node_matches.tsv": "TAXI_",
    "instance_node_matches.tsv": "INSTANCE_",
}


def load_renames():
    """source id -> Modern id: the map tools/gen_modern_nodes.py wrote (tools/modern_ids.py has the rules)."""
    return modern_ids.load()


def known_node_ids():
    ids = set()
    for path in sorted((OUT).glob("Nodes_*.lua")):
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line.startswith('{ id = "'):
                ids.add(line.split('"')[1])
    return ids


# The keys of addon.HOLIDAYS (Data/Modern/Game.lua): what an edge's `holiday` requirement must say.
HOLIDAY_KEYS = {"love_is_in_the_air", "darkmoon_faire", "feast_of_winters_veil"}


def holiday_key(name):
    """The old data names a holiday as the calendar does ("Darkmoon Faire"); the engine's table is keyed
    darkmoon_faire. Lower case, apostrophes dropped, other runs of non-letters to one underscore
    ("Feast of Winter's Veil" -> feast_of_winters_veil). Anything that isn't a known key is an error here,
    not a silently dead edge in the game."""
    key = re.sub(r"[^a-z0-9]+", "_", str(name).lower().replace("'", "")).strip("_")
    if key not in HOLIDAY_KEYS:
        raise SystemExit(f"holiday '{name}' -> '{key}' is not an addon.HOLIDAYS key {sorted(HOLIDAY_KEYS)}; "
                         "add it to Data/Modern/Game.lua and HOLIDAY_KEYS in this script, or fix the source data")
    return key


def node_places():
    """{ node id: (container path, mapID) } from the converted Nodes_*.lua."""
    places = {}
    for path in sorted(OUT.glob("Nodes_*.lua")):
        for line in path.read_text(encoding="utf-8").splitlines():
            m = re.match(r'\s*\{ id = "([^"]+)", container = "([^"]+)", mapID = (\d+)', line)
            if m:
                places[m.group(1)] = (m.group(2), int(m.group(3)))
    return places


def phase_sides():
    """{ art id: group } from the phase tags gen_modern_nodes.py wrote into Containers.lua."""
    sides = {}
    text = (OUT / "Containers.lua").read_text(encoding="utf-8")
    for m in re.finditer(r'phaseGroup = "([^"]+)", phaseSide = (\d+)', text):
        sides[int(m.group(2))] = m.group(1)
    return sides


def phase_group_of(node_id, places, sides):
    """The phase group a node's container is a side of, or None."""
    container, _map_id = places.get(node_id, ("", 0))
    m = re.search(r"_art(\d+)(\.|$)", container)
    return sides.get(int(m.group(1))) if m else None


def split_phase(reqs, from_id, to_id, sides):
    """(requirements without mapArtID, inPhase or None) -- see the docstring."""
    if not reqs or "mapArtID" not in reqs:
        return reqs, None
    reqs = dict(reqs)
    gate = reqs.pop("mapArtID")
    art_id = int(gate[2] if hasattr(gate, "items") else gate[1])
    if art_id not in sides:
        raise SystemExit(f"edge {from_id} -> {to_id}: mapArtID art {art_id} is no phase group's side")
    return (reqs or None), [sides[art_id], art_id]


def lua_requirements(reqs):
    if reqs is None:
        return None, []
    out = {}
    unknown = []
    for key, value in reqs.items():
        key = RENAME_REQUIREMENT.get(key, key)
        if key in KNOWN_REQUIREMENTS or key in KNOWN_INERT_REQUIREMENTS:
            out[key] = holiday_key(value) if key == "holiday" else value
        else:
            unknown.append(key)
    return out, unknown


def format_value(v):
    if isinstance(v, str):
        return f'"{v}"'
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (list, tuple)):
        return "{ " + ", ".join(format_value(item) for item in v) + " }"
    if hasattr(v, "items"):     # a Lua table -- the mapArtID {mapID, artID} pair, or anyOf
        parts = []
        for k, item in v.items():
            if isinstance(k, int):
                parts.append(format_value(item))
            else:
                parts.append(f"{k} = {format_value(item)}")
        return "{ " + ", ".join(parts) + " }"
    return str(v)


def main():
    lua = LuaRuntime(unpack_returned_tuples=True)
    loadstring = lua.eval("loadstring")
    ns = lua.eval("{}")
    src = SRC.read_text(encoding="utf-8-sig")
    chunk = loadstring(src, "@" + SRC.name)
    if isinstance(chunk, tuple):
        raise SystemExit(f"syntax error in {SRC.name}: {chunk[1]}")
    chunk("Mapzeroth", ns)

    places = node_places()
    sides = phase_sides()
    node_ids = known_node_ids()
    if not node_ids:
        raise SystemExit("no Data/Modern/Nodes_*.lua found -- run tools/gen_modern_nodes.py first")
    renames = load_renames()

    def resolve_id(old_id):
        # The node conversion applies this same rename unless two old ids happened to match
        # the same real id (a rename collision) -- then only the first keeps its new
        # TAXI_<id>/INSTANCE_<id>, and the id actually in Nodes_*.lua is the one to trust either way.
        renamed = renames.get(old_id)
        if renamed and renamed in node_ids:
            return renamed
        return old_id

    lines = ["addon.Edges = {"]
    dangling = []           # (from, to) referencing an unconverted node
    unknown_reqs = {}       # key -> count, for anything not in KNOWN_REQUIREMENTS/INERT
    stray_fields = {}       # field name -> count, for anything not in the schema at all
    phase_gated = 0
    seen_edges = set()      # (from, to, method, requirements) already written
    duplicates = []         # (from, to, method) dropped as an exact repeat of an earlier edge
    cost_filled = {}        # method -> count of edges that got a fallback cost written in
    total = 0

    def edge_identity(e):
        """(from, to, method, requirements) for one old edge, after renames: what makes two edges the same edge
        (the phase gate counts as a requirement here). None when the edge is dropped or dangling (the loop below
        reports those)."""
        from_id, to_id, method = resolve_id(e["from"]), resolve_id(e["to"]), e["method"]
        method = METHOD_RENAME.get(method, method)
        if from_id not in node_ids or to_id not in node_ids:
            return None
        reqs, _ = lua_requirements(e["requirements"])
        return (from_id, to_id, method, tuple(sorted((k, format_value(v)) for k, v in (reqs or {}).items())))

    # The old data has the Stormwind -> Exodar portal twice, once bidirectional and once one-way, and only the
    # one-way is right (the Exodar side's return portal lands in Stormwind's portal room, an edge of its own;
    # captured in game 2026-09-24). Where two edges are the same edge and one says oneway, the one-way copy is
    # the one kept: a missing reverse only lengthens a route, a false one gives a route nobody can travel.
    oneway_keys = {edge_identity(e) for e in ns.Edges.values() if e["oneway"]}
    oneway_keys.discard(None)

    for e in ns.Edges.values():
        keys = set(e.keys())
        for stray in keys - {"from", "to", "method", "cost", "oneway", "requirements", "mapArtID"}:
            stray_fields[stray] = stray_fields.get(stray, 0) + 1
        from_id, to_id, method = resolve_id(e["from"]), resolve_id(e["to"]), e["method"]
        method = METHOD_RENAME.get(method, method)
        if any(resolve_id(d["from"]) == from_id and resolve_id(d["to"]) == to_id and d["method"] == method
               for d in getattr(manual, "DROP_EDGES", [])):
            continue            # replaced by a hand-added route (tools/modern_manual.py)
        if from_id not in node_ids or to_id not in node_ids:
            dangling.append((from_id, to_id))
            continue
        cost = e["cost"]
        if cost is None and method != "walk" and method in FALLBACK_COST:
            cost = FALLBACK_COST[method]
            cost_filled[method] = cost_filled.get(method, 0) + 1
        reqs, unknown = lua_requirements(e["requirements"])
        # An exact repeat (same ends, method and requirements) adds nothing but a second edge for the search
        # to weigh; the first is kept, unless a one-way copy exists, which wins (see oneway_keys above).
        # (Two edges that differ only in requirements, one per faction, are not repeats.)
        edge_key = edge_identity(e)
        if edge_key in seen_edges or (edge_key in oneway_keys and not e["oneway"]):
            duplicates.append((from_id, to_id, method))
            continue
        seen_edges.add(edge_key)
        for key in unknown:
            unknown_reqs[key] = unknown_reqs.get(key, 0) + 1
        reqs, in_phase = split_phase(reqs, from_id, to_id, sides)
        overrides = None
        if method == "phaseswitch":
            overrides = phase_group_of(to_id, places, sides)
            if not overrides or phase_group_of(from_id, places, sides) != overrides:
                raise SystemExit(f"phaseswitch edge {from_id} -> {to_id}: its ends are not two sides of one phase group")
            in_phase = None         # Zidormi is how the side changes: she is there on both
        if in_phase:
            phase_gated += 1

        parts = [f'from = "{from_id}"', f'to = "{to_id}"', f'method = "{method}"']
        if cost is not None:
            parts.append(f"cost = {cost}")
        if e["oneway"]:
            parts.append("oneway = true")
        if overrides:
            parts.append(f'overridesPhase = {{ "{overrides}" }}')
        if in_phase:
            parts.append(f'inPhase = {{ "{in_phase[0]}", {in_phase[1]} }}')
        if reqs:
            req_parts = ", ".join(f"{k} = {format_value(v)}" for k, v in reqs.items())
            parts.append(f"requirements = {{ {req_parts} }}")
        lines.append(f"    {{ {', '.join(parts)} }},")
        total += 1

    # Hand-added edges (tools/modern_manual.py).
    for me in manual.EDGES:
        me_from, me_to = resolve_id(me["from"]), resolve_id(me["to"])     # written in source ids, like the old data
        if me_from not in node_ids or me_to not in node_ids:
            raise SystemExit(f"manual edge {me['from']} -> {me['to']} names a node that doesn't exist")
        parts = [f'from = "{me_from}"', f'to = "{me_to}"', f'method = "{me["method"]}"']
        if me.get("cost") is not None:
            parts.append(f'cost = {me["cost"]}')
        if me.get("oneway"):
            parts.append("oneway = true")
        if me.get("inPhase"):
            parts.append(f'inPhase = {{ "{me["inPhase"][0]}", {me["inPhase"][1]} }}')
        if me.get("requirements"):
            req_parts = ", ".join(f"{k} = {format_value(v)}" for k, v in me["requirements"].items())
            parts.append(f"requirements = {{ {req_parts} }}")
        if me.get("loadingScreens") is not None:
            parts.append(f'loadingScreens = {me["loadingScreens"]}')
        lines.append(f"    {{ {', '.join(parts)} }}, -- hand-added: tools/modern_manual.py")
        total += 1

    lines.append("}")
    (OUT / "Edges.lua").write_text(
        "-- Edges.lua (Modern) -- GENERATED by tools/gen_modern_edges.py from the original\n"
        "-- addon's Mapzeroth_Data_Edges.lua, do not hand-edit. See the script's own docstring\n"
        "-- for the conversion rules (cost fallbacks, requirement renames, phase gates as inPhase,\n"
        "-- Zidormi's overridesPhase) and Data/Modern/CONVERSION_NOTES.md for\n"
        "-- what's still open.\n\n"
        "local addonName, addon = ...\n"
        "if addon.RULESET ~= \"modern\" then return end   -- one addon for both games: this data is Modern's (Constants.lua)\n\n"
        + "\n".join(lines) + "\n",
        encoding="utf-8",
    )

    notes = [
        "",
        "## Edge conversion (tools/gen_modern_edges.py)",
        "",
        f"{total} edges written.",
        "",
        f"- Cost filled in from the old flat per-method default (see the script's docstring) "
        f"for: " + (", ".join(f"{m} ({n})" for m, n in sorted(cost_filled.items())) if cost_filled else "none") + ".",
        f"- {phase_gated} edges carry `inPhase` (the old `mapArtID` gate): usable only on that side",
        "  of their phase group. Zidormi's `phaseswitch` edges carry `overridesPhase` instead.",
    ]
    if dangling:
        notes.append(f"- {len(dangling)} edge(s) dropped: `from`/`to` didn't resolve to a converted node")
        notes.append("  (a node this pass hasn't reached, or the old data referencing something that")
        notes.append("  no longer exists -- worth checking by hand, not assumed stale):")
        notes.append("")
        for f, t in dangling:
            notes.append(f"  - `{f}` -> `{t}`")
    else:
        notes.append("- No dangling `from`/`to`: every edge resolved to a node from the conversion pass.")
    if duplicates:
        notes.append(f"- {len(duplicates)} exact duplicate edge(s) dropped (same `from`, `to`, method and "
                     "requirements as an earlier edge; the first is kept):")
        for f, t, m in duplicates:
            notes.append(f"  - `{f}` -> `{t}` ({m})")
    if unknown_reqs:
        notes.append(f"- Unrecognized requirement key(s), dropped from their edge (not carried through,")
        notes.append("  unlike `mapArtID` -- these aren't a known concept in either engine, worth a look):")
        for key, count in sorted(unknown_reqs.items()):
            notes.append(f"  - `{key}` ({count})")
    else:
        notes.append("- No unrecognized requirement keys.")
    if stray_fields:
        notes.append("- Stray field(s) on some edge, not part of the schema, dropped:")
        for key, count in sorted(stray_fields.items()):
            notes.append(f"  - `{key}` ({count})")

    # Replaces only this script's own section (conversion_notes.py); everything else in the file stays.
    conversion_notes.write_section(OUT / "CONVERSION_NOTES.md",
                                   "## Edge conversion (tools/gen_modern_edges.py)", notes)

    print(f"wrote {total} edges to {OUT / 'Edges.lua'}")
    print(f"{len(duplicates)} duplicate(s) dropped")
    print(f"{len(dangling)} dangling, {phase_gated} phase-gated (inPhase), "
          f"{sum(unknown_reqs.values())} unrecognized requirement(s), {sum(stray_fields.values())} stray field(s)")


if __name__ == "__main__":
    main()
