"""Generates Data/Forever/ClassSpells.lua: what each class's trainers teach, and at what level.

The source is Wowhead's Forever NPC pages: each class trainer's "Teaches" list gives every
ability with its spell id, rank, required level, training cost and (for racial abilities)
a race mask. A class's trainers all teach the same, except that a racial ability is only
taught in the race's own city (priests', on Forever), so one trainer per faction is read,
and for priests one per capital, and their lists merged.

Pages are cached in tools/class_source/<npc id>.json, so a rerun only fetches NPCs it
hasn't seen; --refresh fetches them all again. Wowhead answers 403 when asked faster than
about one page per two seconds, so this waits between pages and stops on a 403.

    python tools/gen_class_spells.py [--refresh]
"""
import json
import pathlib
import re
import sys
import time
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
CACHE = ROOT / "tools" / "class_source"
POIS = ROOT / "Data" / "Forever" / "Pois.lua"
OUT = ROOT / "Data" / "Forever" / "ClassSpells.lua"

CLASS_TOKENS = ["WARRIOR", "PALADIN", "HUNTER", "ROGUE", "PRIEST", "SHAMAN", "MAGE", "WARLOCK", "DRUID"]
CAPITALS = {"stormwind", "ironforge", "darnassus", "orgrimmar", "undercity", "thunder_bluff"}
DELAY = 2.5


ALLIANCE = {"stormwind", "ironforge", "darnassus"}
PER_CAPITAL = {"PRIEST"}      # classes with racial abilities: a trainer from every capital


def trainer_npcs():
    """class token -> NPC ids to read for that class: the first trainer in each capital (PER_CAPITAL), else in
    the first capital of each faction, from Pois.lua."""
    found = {token: [] for token in CLASS_TOKENS}
    seen = set()
    for line in POIS.read_text(encoding="utf-8").splitlines():
        m = re.search(r'trainer = "([A-Z]+)"', line)
        city = re.search(r'city = "([a-z_]+)"', line)
        if not m or m.group(1) not in found or not city or city.group(1) not in CAPITALS:
            continue
        token, where = m.group(1), city.group(1)
        key = (token, where if token in PER_CAPITAL else where in ALLIANCE)
        npc = re.search(r"\{ id = (\d+)", line)
        if npc and key not in seen:
            seen.add(key)
            found[token].append(int(npc.group(1)))
    return found


def listview(html, name):
    """The data array of the page's Listview with this id, or None."""
    i = html.find(f"id: '{name}'")
    if i < 0:
        return None
    start = html.index("data: [", i) + 6
    depth = 0
    for k in range(start, len(html)):
        c = html[k]
        if c == "[":
            depth += 1
        elif c == "]":
            depth -= 1
            if depth == 0:
                return json.loads(html[start:k + 1])


def fetch(npc):
    req = urllib.request.Request(f"https://www.wowhead.com/forever/npc={npc}", headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req) as resp:
        html = resp.read().decode("utf-8")
    rows = listview(html, "teaches-ability") or []
    keep = ("id", "name", "rank", "level", "trainingcost", "reqrace", "reqclass")
    return [{k: r[k] for k in keep if k in r} for r in rows]


def load(npc, refresh):
    path = CACHE / f"{npc}.json"
    if path.exists() and not refresh:
        return json.loads(path.read_text(encoding="utf-8"))
    try:
        rows = fetch(npc)
    except urllib.error.HTTPError as err:
        if err.code == 403:
            sys.exit(f"Wowhead refused NPC {npc} (403): too fast. Wait a while and rerun; the pages so far are cached.")
        raise
    CACHE.mkdir(exist_ok=True)
    path.write_text(json.dumps(rows, indent=1, ensure_ascii=False), encoding="utf-8")
    print(f"  fetched NPC {npc}: {len(rows)} abilities")
    time.sleep(DELAY)
    return rows


def rank_number(rank):
    m = re.match(r"Rank (\d+)$", rank or "")
    return int(m.group(1)) if m else None


def main():
    refresh = "--refresh" in sys.argv
    spells = {}
    for token, npcs in trainer_npcs().items():
        merged = {}
        for npc in npcs:
            for row in load(npc, refresh):
                merged.setdefault(row["id"], row)
        spells[token] = merged
        print(f"{token}: {len(npcs)} trainers, {len(merged)} abilities")

    named = ["Written by gen_class_spells.py each run; not read by the addon.",
             "Every row of Data/Forever/ClassSpells.lua with its ability's name (spell id, required level, cost in copper).",
             "From Wowhead's Forever trainer pages: every class trainer in the six capitals, merged.", ""]
    out = [
        "-- ClassSpells.lua (Forever) -- GENERATED by tools/gen_class_spells.py, do not hand-edit.",
        "--",
        "-- What each class's trainers teach: { spell id, required level, cost in copper }, with",
        "--   races   the race mask, for an ability only some races learn (1 Human, 2 Orc, 4 Dwarf, 8 Night Elf,",
        "--           16 Undead, 32 Tauren, 64 Gnome, 128 Troll ...);",
        "--   after   the rank before it, when a trainer teaches that too (it has to be learned first);",
        "--   owned   true when the rank before comes from somewhere else (a talent, a quest): only a player",
        "--           who already has the ability can learn this rank.",
        "",
        "local addonName, addon = ...",
        'if addon.RULESET ~= "forever" then return end   -- one addon for both games: this data is Forever\'s (Constants.lua)',
        "",
        "addon.ClassSpells = {",
    ]
    for token in CLASS_TOKENS:
        merged = spells[token]
        # Ranks of one ability: by name and race mask (two races' versions of a racial are separate chains).
        chains = {}
        for row in merged.values():
            n = rank_number(row.get("rank"))
            if n is not None:
                chains.setdefault((row["name"], row.get("reqrace")), {})[n] = row["id"]
        out.append(f"    {token} = {{")
        named.append(f"{token}:")
        for row in sorted(merged.values(), key=lambda r: (r["level"], r["name"], rank_number(r.get("rank")) or 0)):
            parts = [str(row["id"]), str(row["level"]), str(row.get("trainingcost", 0))]
            if row.get("reqrace"):
                parts.append(f"races = {row['reqrace']}")
            n = rank_number(row.get("rank"))
            if n and n > 1:
                before = chains[(row["name"], row.get("reqrace"))].get(n - 1)
                parts.append(f"after = {before}" if before else "owned = true")
            label = row["name"] + (f" ({row['rank']})" if row.get("rank") else "")
            out.append(f"        {{ {', '.join(parts)} }},")
            named.append(f"  {row['id']:>8}  level {row['level']:>2}  {row.get('trainingcost', 0):>6}c  {label}")
        out.append("    },")
    out.append("}")
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    (ROOT / "tools" / "class_spells_report.txt").write_text("\n".join(named) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
