"""tools/match_modern_instance_nodes.py -- matches the old addon's *_DUNGEON/*_RAID nodes
against the real retail JournalInstance table
(tools/modern_source/journal_instance_retail.csv, pulled from
https://wago.tools/db2/JournalInstance/csv) by name, so they can be renamed to
INSTANCE_<journalInstanceID> and get a free, properly-localized name from the client at
runtime (EJ_GetInstanceInfo, the Dungeon Journal API -- see NodeNames.lua) instead of
needing a hand-authored override. JournalInstance was picked over AreaTable (the more
obvious "an entrance is a place with an area name" source, and what Forever's own
instance entrances already use, per docs/DESIGN.md section 5a) because AreaTable's 10k
rows have massive name collisions (the same zone name reused across live/Timewalking/
wings/expansions -- 57% of these nodes matched more than one row); JournalInstance's ~216
rows are close to 1:1 with real instances and matched 95% with a single confident hit.

    python tools/match_modern_instance_nodes.py
"""
import pathlib
import re
from lupa.lua51 import LuaRuntime

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = pathlib.Path(r"C:\Users\shaun\Documents\Claude\Mapzeroth\Mapzeroth\Data")
JOURNAL_CSV = ROOT / "tools" / "modern_source" / "journal_instance_retail.csv"
OUT = ROOT / "tools" / "modern_source" / "instance_node_matches.tsv"

FILES = [
    "Mapzeroth_Data_Nodes_EK.lua", "Mapzeroth_Data_Nodes_Kalimdor.lua",
    "Mapzeroth_Data_Nodes_Outlands.lua", "Mapzeroth_Data_Nodes_Northrend.lua",
    "Mapzeroth_Data_Nodes_Pandaria.lua", "Mapzeroth_Data_Nodes_BrokenIsles.lua",
    "Mapzeroth_Data_Nodes_Draenor.lua", "Mapzeroth_Data_Nodes_DragonIsles.lua",
    "Mapzeroth_Data_Nodes_KhazAlgar.lua", "Mapzeroth_Data_Nodes_Shadowlands.lua",
    "Mapzeroth_Data_Nodes_Zandalar.lua", "Mapzeroth_Data_Nodes_Argus.lua",
    "Mapzeroth_Data_Nodes_BfA.lua", "Mapzeroth_Data_Nodes_IsolatedMaps.lua",
]


def norm(name):
    name = re.sub(r"\s*\([^)]*\)\s*$", "", name.strip())   # trailing "(Burning Crusade)"
    name = re.sub(r"^the\s+", "", name, flags=re.IGNORECASE)   # either side's leading "The "
    return name.strip().lower()


def main():
    by_name = {}
    with open(JOURNAL_CSV, encoding="utf-8-sig", newline="") as f:
        import csv
        for row in csv.DictReader(f):
            key = norm(row["Name_lang"])
            if key:
                by_name.setdefault(key, []).append(row["ID"])

    lua = LuaRuntime(unpack_returned_tuples=True)
    loadstring = lua.eval("loadstring")

    rows = []
    counts = {"one": 0, "zero": 0, "many": 0}
    for filename in FILES:
        ns = lua.eval("{}")
        src = (SRC / filename).read_text(encoding="utf-8-sig")
        chunk = loadstring(src, "@" + filename)
        if isinstance(chunk, tuple):
            raise SystemExit(f"syntax error in {filename}: {chunk[1]}")
        chunk("Mapzeroth", ns)
        for group_name, group in ns.Nodes.items():
            for node_id, node in group.items():
                if not (node_id.endswith("_DUNGEON") or node_id.endswith("_RAID")):
                    continue
                name = node["name"] or ""
                candidates = by_name.get(norm(name), [])
                verdict = "one" if len(candidates) == 1 else ("zero" if not candidates else "many")
                counts[verdict] += 1
                rows.append((node_id, verdict, ",".join(candidates), name))

    rows.sort(key=lambda r: (r[1] != "one", r[0]))
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("# old node id\tverdict (one|zero|many)\tjournalInstanceID(s)\told name\n")
        f.write("# GENERATED by tools/match_modern_instance_nodes.py -- review \"zero\" and \"many\" rows\n")
        f.write("# by hand (a wing/Timewalking-variant tiebreak, or it's genuinely not in the current\n")
        f.write("# Dungeon Journal any more) and either fix the ID here or leave the row as-is;\n")
        f.write("# gen_modern_nodes.py only acts on \"one\" rows.\n")
        for node_id, verdict, ids, name in rows:
            f.write(f"{node_id}\t{verdict}\t{ids}\t{name}\n")

    print(f"{counts['one']} confident, {counts['zero']} no match, {counts['many']} ambiguous "
          f"(of {sum(counts.values())} total) -- see {OUT}")


if __name__ == "__main__":
    main()
